# Perform differential expression analysis between RA patients

**Author: Caroline Larkin**

**Research Group: Gottschalk Lab, Department of Immunology, University of Pittsburgh**

Notebook based on [link](https://liana-py.readthedocs.io/en/latest/notebooks/targeted.html)

In [1]:
import numpy as np
import pandas as pd
import anndata as ad 
import scanpy as sc

import celltypist
from celltypist import models

import liana as li

# Import DESeq2
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats

import matplotlib.pyplot as plt
import seaborn as sns 

#sample_ids = ["SA149P", "SA154", "SA220", "SA222", "SA227", "SA159", "SA168", "SA225"]
#sample_labels = ["UPA", "UPA", "Naive", "Resistant", "Resistant", "Remission", "Remission", "Remission"] 

sample_ids = ["SA220", "SA159", "SA168", "SA225"]
sample_labels = ["Naive", "Remission", "Remission", "Remission"] 
CONTROL_GROUP = "Naive"

output_fname = "../Data/DECCC_remission_v_naive_momac-targets.csv"
data_dir = "../Data/EMATB8322/"

# Download base models from celltypist
models.download_models()

/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/celltypist/classifier.py:11: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  from scanpy import __version__ as scv
📂 Storing models in /ihome/rgottschalk/cil8/.celltypist/data/models
⏩ Skipping [1/60]: Immune_All_Low.pkl (file exists)
⏩ Skipping [2/60]: Immune_All_High.pkl (file exists)
⏩ Skipping [3/60]: Adult_COVID19_PBMC.pkl (file exists)
⏩ Skipping [4/60]: Adult_CynomolgusMacaque_Hippocampus.pkl (file exists)
⏩ Skipping [5/60]: Adult_Human_MTG.pkl (file exists)
⏩ Skipping [6/60]: Adult_Human_PancreaticIslet.pkl (file exists)
⏩ Skipping [7/60]: Adult_Human_PrefrontalCortex.pkl (file exists)
⏩ Skipping [8/60]: Adult_Human_Skin.pkl (file exists)
⏩ Skipping [9/60]: Adult_Human_Vascular.pkl (file exists)
⏩ Skipping [10/60]: Adult_Mouse_Gut.pkl (file exists)
⏩ Skipping [11/60]: Adult_Mouse_OlfactoryBulb.pkl (file exists)
⏩ Skipping [12/60]: Adult_Pig_Hippocampus.pkl (file exists)
⏩ Skipping [13/60]: Adult_RhesusMacaque_Hippocampus.pkl (file exists)
⏩ Skipping [14/60]: Adult_cHSPCs_Illumina.pkl (file exists)
⏩ Skipping [15/60]: Adult_cHSPCs_Ultima.pkl (file exists)
⏩ Skipping [16/60]: Autopsy_COVID19_Lung.pkl (file exists)
⏩ Skipping [17/60]: COVID19_HumanChallenge_Blood.pkl (file exists)
⏩ Skipping [18/60]: COVID19_Immune_Landscape.pkl (file exists)
⏩ Skipping [19/60]: Cells_Adult_Breast.pkl (file exists)
⏩ Skipping [20/60]: Cells_Fetal_Lung.pkl (file exists)
⏩ Skipping [21/60]: Cells_Human_Tonsil.pkl (file exists)
⏩ Skipping [22/60]: Cells_Intestinal_Tract.pkl (file exists)
⏩ Skipping [23/60]: Cells_Lung_Airway.pkl (file exists)
⏩ Skipping [24/60]: Developing_Human_Brain.pkl (file exists)
⏩ Skipping [25/60]: Developing_Human_Gonads.pkl (file exists)
⏩ Skipping [26/60]: Developing_Human_Hippocampus.pkl (file exists)
⏩ Skipping [27/60]: Developing_Human_Organs.pkl (file exists)
⏩ Skipping [28/60]: Developing_Human_Thymus.pkl (file exists)
⏩ Skipping [29/60]: Developing_Mouse_Brain.pkl (file exists)
⏩ Skipping [30/60]: Developing_Mouse_Hippocampus.pkl (file exists)
⏩ Skipping [31/60]: Fetal_Human_AdrenalGlands.pkl (file exists)
⏩ Skipping [32/60]: Fetal_Human_Pancreas.pkl (file exists)
⏩ Skipping [33/60]: Fetal_Human_Pituitary.pkl (file exists)
⏩ Skipping [34/60]: Fetal_Human_Retina.pkl (file exists)
⏩ Skipping [35/60]: Fetal_Human_Skin.pkl (file exists)
⏩ Skipping [36/60]: Healthy_Adult_Heart.pkl (file exists)
⏩ Skipping [37/60]: Healthy_COVID19_PBMC.pkl (file exists)
⏩ Skipping [38/60]: Healthy_Human_Liver.pkl (file exists)
⏩ Skipping [39/60]: Healthy_Mouse_Liver.pkl (file exists)
⏩ Skipping [40/60]: Human_AdultAged_Hippocampus.pkl (file exists)
⏩ Skipping [41/60]: Human_Colorectal_Cancer.pkl (file exists)
⏩ Skipping [42/60]: Human_Developmental_Retina.pkl (file exists)
⏩ Skipping [43/60]: Human_Embryonic_YolkSac.pkl (file exists)
⏩ Skipping [44/60]: Human_Endometrium_Atlas.pkl (file exists)
⏩ Skipping [45/60]: Human_IPF_Lung.pkl (file exists)
⏩ Skipping [46/60]: Human_Longitudinal_Hippocampus.pkl (file exists)
⏩ Skipping [47/60]: Human_Lung_Atlas.pkl (file exists)
⏩ Skipping [48/60]: Human_PF_Lung.pkl (file exists)
⏩ Skipping [49/60]: Human_Placenta_Decidua.pkl (file exists)
⏩ Skipping [50/60]: Lethal_COVID19_Lung.pkl (file exists)
⏩ Skipping [51/60]: Mouse_Dendritic_Subtypes.pkl (file exists)
⏩ Skipping [52/60]: Mouse_Dentate_Gyrus.pkl (file exists)
⏩ Skipping [53/60]: Mouse_Isocortex_Hippocampus.pkl (file exists)
⏩ Skipping [54/60]: Mouse_Postnatal_DentateGyrus.pkl (file exists)
⏩ Skipping [55/60]: Mouse_Whole_Brain.pkl (file exists)
⏩ Skipping [56/60]: Nuclei_Human_InnerEar.pkl (file exists)
⏩ Skipping [57/60]: Nuclei_Lung_Airway.pkl (file exists)
⏩ Skipping [58/60]: PaediatricAdult_COVID19_Airway.pkl (file exists)
⏩ Skipping [59/60]: PaediatricAdult_COVID19_PBMC.pkl (file exists)
⏩ Skipping [60/60]: Pan_Fetal_Human.pkl (file exists)

## 1. Load data

In [2]:
# Load celltypist immune model
model = models.Model.load(model = "Immune_All_High.pkl")

mac_subtype_df = pd.read_csv("../Data/macrophage_subtype_designation.csv", index_col=0)
mac_subtype_df

     Mac Subtype      Group Sample             Barcode
0         Mo-mac      Naive  SA220  AAACCTGCACCCATGG-1
1            TRM      Naive  SA220  AAACGGGTCAACGAAA-1
2            TRM      Naive  SA220  AAAGCAAAGTAAGTAC-1
3         Mo-mac      Naive  SA220  AAATGCCGTCCCTTGT-1
4            TRM      Naive  SA220  AACCATGTCTTGGGTA-1
...          ...        ...    ...                 ...
4712      Mo-mac  Remission  SA225  TGGGAAGAGAGTACAT-1
4713         TRM  Remission  SA225  TGGGCGTGTCACACGC-1
4714      Mo-mac  Remission  SA225  TTAGTTCTCTGTTGAG-1
4715      Mo-mac  Remission  SA225  TTATGCTCAACACGCC-1
4716      Mo-mac  Remission  SA225  TTGGAACAGGTGTGGT-1

[4717 rows x 4 columns]

In [3]:
ads = []
for id, label in zip(sample_ids, sample_labels):
    cur_ad = sc.read_mtx(filename=f"{data_dir}{id}/processed_counts.mtx").transpose()
    gene_names = pd.read_csv(f"{data_dir}{id}/processed_gene_names.csv", header=None)
    cur_ad.var_names = gene_names.values.flatten()
    print()#print(gene_names.values.flatten())
    barcodes = pd.read_csv(f"{data_dir}{id}/processed_metadata.csv", usecols=["barcode"])
    cur_ad.obs_names = barcodes.values.flatten()
    cur_ad.obs_names_make_unique()
    cur_ad.obs["Group"] = [label]* len(barcodes)
    cur_ad.obs["Sample"] = [id] * len(barcodes)
    display(cur_ad)

    # create a temporary copy of adata to preprocess
    temp = cur_ad.copy()
    # Normalizing to median total counts
    sc.pp.normalize_total(temp, target_sum=10000)
    # Logarithmize the data
    sc.pp.log1p(temp)

    predictions = celltypist.annotate(temp, model=model)
    new_ad = predictions.to_adata();
    cur_ad.obs["cell_type"] = new_ad.obs["predicted_labels"]
    cell_counts = cur_ad.obs["cell_type"].value_counts()
    # removing cell types with low counts
    #print(cell_counts)
    keep_cell_types = cell_counts[cell_counts.values > 10]
    #print(keep_cell_types.index.values)
    cur_ad = cur_ad[cur_ad.obs["cell_type"].isin(keep_cell_types.index.values)]
    display(cur_ad)
    #break
    ads.append(cur_ad); 
    del temp
    del new_ad

AnnData object with n_obs × n_vars = 1832 × 16171
    obs: 'Group', 'Sample'

🔬 Input data has 1832 cells and 16171 genes
🔗 Matching reference genes in the model
🧬 4688 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 1822 × 16171
    obs: 'Group', 'Sample', 'cell_type'

AnnData object with n_obs × n_vars = 3206 × 16155
    obs: 'Group', 'Sample'

🔬 Input data has 3206 cells and 16155 genes
🔗 Matching reference genes in the model
🧬 4850 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 3195 × 16155
    obs: 'Group', 'Sample', 'cell_type'

AnnData object with n_obs × n_vars = 5058 × 17498
    obs: 'Group', 'Sample'

🔬 Input data has 5058 cells and 17498 genes
🔗 Matching reference genes in the model
🧬 5011 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 5042 × 17498
    obs: 'Group', 'Sample', 'cell_type'

AnnData object with n_obs × n_vars = 1783 × 13829
    obs: 'Group', 'Sample'

🔬 Input data has 1783 cells and 13829 genes
🔗 Matching reference genes in the model
🧬 4345 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 1765 × 13829
    obs: 'Group', 'Sample', 'cell_type'

In [4]:
adata = sc.concat(ads, merge="same", join="inner")
adata.obs_names_make_unique()
#adata.X.dtype = np.int64
adata.X = adata.X.toarray()
adata.X[np.isnan(adata.X)] = 0 
display(adata)

AnnData object with n_obs × n_vars = 11824 × 13480
    obs: 'Group', 'Sample', 'cell_type'

In [5]:
# Overwrite the macrophages with the specific subtype from the dataframe file
mac_mask = adata.obs["cell_type"] == "Macrophages"
df_mac = (
    mac_subtype_df.set_index(["Barcode", "Sample"])
      .loc[:, "Mac Subtype"])
print(df_mac)

adata_index = pd.MultiIndex.from_arrays(
    [adata.obs_names, adata.obs["Sample"]],
    names=["Barcode", "Sample"]
)
print(adata_index)

# Create a Series aligned to AnnData
mac_subtypes = df_mac.reindex(adata_index)
print(mac_subtypes.notna())
print("-----------")
print(mac_mask)

new_categories = mac_subtypes.dropna().unique()

adata.obs["cell_type"] = adata.obs["cell_type"].cat.add_categories(new_categories)

overwrite_mask = (
    mac_mask.to_numpy() &
    mac_subtypes.notna().to_numpy()
)

adata.obs.loc[overwrite_mask, "cell_type"] = mac_subtypes.to_numpy()[overwrite_mask]

# How many macrophages were relabeled?
overwrite_mask.sum()

# Check remaining generic macrophages
#(adata.obs["cell_type"] == "Macrophages").sum()

# Inspect label distribution
adata.obs["cell_type"].value_counts()

Barcode             Sample
AAACCTGCACCCATGG-1  SA220     Mo-mac
AAACGGGTCAACGAAA-1  SA220        TRM
AAAGCAAAGTAAGTAC-1  SA220        TRM
AAATGCCGTCCCTTGT-1  SA220     Mo-mac
AACCATGTCTTGGGTA-1  SA220        TRM
                               ...
TGGGAAGAGAGTACAT-1  SA225     Mo-mac
TGGGCGTGTCACACGC-1  SA225        TRM
TTAGTTCTCTGTTGAG-1  SA225     Mo-mac
TTATGCTCAACACGCC-1  SA225     Mo-mac
TTGGAACAGGTGTGGT-1  SA225     Mo-mac
Name: Mac Subtype, Length: 4717, dtype: object
MultiIndex([('AAACCTGAGCGCTTAT-1', 'SA220'),
            ('AAACCTGCACCCATGG-1', 'SA220'),
            ('AAACGGGAGACTGGGT-1', 'SA220'),
            ('AAACGGGTCAACGAAA-1', 'SA220'),
            ('AAACGGGTCCTTTCGG-1', 'SA220'),
            ('AAAGATGAGAAACCGC-1', 'SA220'),
            ('AAAGATGAGAAAGTGG-1', 'SA220'),
            ('AAAGATGAGTATTGGA-1', 'SA220'),
            ('AAAGATGGTGCTGTAT-1', 'SA220'),
            ('AAAGATGTCGGCGGTT-1', 'SA220'),
            ...
            ('TTTCCTCCAGTATAAG-1', 'SA225'),
            ('TTTGCGCAGAATGTTG-1', 'SA225'),
            ('TTTGCGCCAGTTTACG-1', 'SA225'),
            ('TTTGCGCGTGAAAGAG-1', 'SA225'),
            ('TTTGGTTAGATGCCTT-1', 'SA225'),
            ('TTTGGTTAGCAAATCA-1', 'SA225'),
            ('TTTGGTTAGTGTCTCA-1', 'SA225'),
            ('TTTGGTTCACGCTTTC-1', 'SA225'),
            ('TTTGGTTTCAGGCGAA-1', 'SA225'),
            ('TTTGGTTTCATGCATG-1', 'SA225')],
           names=['Barcode', 'Sample'], length=11824)
Barcode             Sample
AAACCTGAGCGCTTAT-1  SA220     False
AAACCTGCACCCATGG-1  SA220      True
AAACGGGAGACTGGGT-1  SA220     False
AAACGGGTCAACGAAA-1  SA220      True
AAACGGGTCCTTTCGG-1  SA220     False
                              ...
TTTGGTTAGCAAATCA-1  SA225     False
TTTGGTTAGTGTCTCA-1  SA225     False
TTTGGTTCACGCTTTC-1  SA225     False
TTTGGTTTCAGGCGAA-1  SA225     False
TTTGGTTTCATGCATG-1  SA225     False
Name: Mac Subtype, Length: 11824, dtype: bool
-----------
AAACCTGAGCGCTTAT-1    False
AAACCTGCACCCATGG-1     True
AAACGGGAGACTGGGT-1    False
AAACGGGTCAACGAAA-1     True
AAACGGGTCCTTTCGG-1    False
                      ...
TTTGGTTAGCAAATCA-1    False
TTTGGTTAGTGTCTCA-1    False
TTTGGTTCACGCTTTC-1    False
TTTGGTTTCAGGCGAA-1    False
TTTGGTTTCATGCATG-1    False
Name: cell_type, Length: 11824, dtype: bool

cell_type
Fibroblasts                   3500
Endothelial cells             2190
Mo-mac                        1627
T cells                       1543
TRM                           1103
DC                             530
Monocytes                      355
B cells                        321
ILC                            305
Mast cells                     121
Plasma cells                   109
Epithelial cells                84
Macrophages                     23
Double-positive thymocytes      13
Name: count, dtype: int64

In [6]:
sets = [set(x.var_names) for x in ads]
union = list(sets[0].intersection(*sets[1:]))
print("The total number of genes included in these samples is: ", len(union))

The total number of genes included in these samples is:  13480

In [7]:
condition_key = "Group"
groupby = "cell_type"
dea_results = {}
quiet = True

for cell_group in adata.obs[groupby].unique():
    # Select cell profiles
    ctdata = adata[adata.obs[groupby] == cell_group].copy()
    print("\n\n\n\n\n-------------------------------------------------------------------------------------\n\nHERE", cell_group); 
    print("CELL TYPE: ", cell_group, ctdata.obs["Group"].unique())

    # Check to see if cell type is present in both Groups
    if(len(np.unique(ctdata.obs["Group"])) < 2):
        # remove it from the dataset and continue 
        adata = adata[adata.obs[groupby] != cell_group]
        continue
        
    # Build DESeq2 object
    # NOTE: this data is actually paired, so one could consider fitting the patient label as a confounder
    dds = DeseqDataSet(
    	adata=ctdata,
    	design_factors=condition_key,
    	ref_level=[condition_key, CONTROL_GROUP], # set control as reference
    	refit_cooks=True,
    )

    # Compute LFCs
    dds.deseq2()
    # Contrast between stim and ctrl
    stat_res = DeseqStats(dds, contrast=[condition_key, 'Remission', 'Naive'])
    # Compute Wald test
    stat_res.summary()
    # Shrink LFCs
    stat_res.lfc_shrink(coeff='Group[T.Remission]') # {condition_key}_cond_vs_ref
    #stat_res.lfc_shrink(coeff='condition_Resistant_vs_Naive') # {condition_key}_cond_vs_ref

    dea_results[cell_group] = stat_res.results_df;

-------------------------------------------------------------------------------------

HERE Fibroblasts
CELL TYPE:  Fibroblasts ['Naive' 'Remission']

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.51 seconds.

Fitting dispersions...
... done in 2.26 seconds.

Fitting dispersion trend curve...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 2.31 seconds.

Fitting LFCs...
... done in 2.25 seconds.

Calculating cook's distance...
... done in 1.82 seconds.

Replacing 17 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.15 seconds.

Running Wald tests...
... done in 0.81 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
FO538757.2      0.109863        0.746883  0.243685   3.064956  2.177020e-03
AP006222.2      0.166597        0.288351  0.166497   1.731872  8.329643e-02
RP4-669L17.10   0.004866        0.721261  2.211540   0.326135  7.443221e-01
RP11-206L10.9   0.025799        0.714024  0.634808   1.124787  2.606792e-01
FAM87B          0.021720        0.656957  0.800819   0.820357  4.120125e-01
...                  ...             ...       ...        ...           ...
MT-ND6          0.326766        0.416713  0.160609   2.594581  9.470641e-03
MT-CYB         27.295743       -0.411149  0.038270 -10.743383  6.366745e-27
AL592183.1      0.024681        0.694283  0.754164   0.920599  3.572598e-01
AC007325.4      0.038791        0.578147  0.519371   1.113166  2.656372e-01
AC240274.1      0.088527        0.161312  0.272129   0.592777  5.533304e-01

                       padj
FO538757.2     7.405836e-03
AP006222.2     1.295780e-01
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6         2.657545e-02
MT-CYB         9.038115e-26
AL592183.1              NaN
AC007325.4              NaN
AC240274.1     6.024862e-01

[13480 rows x 6 columns]

... done in 1.63 seconds.

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
FO538757.2      0.109863        0.373622  0.282069   3.064956  2.177020e-03
AP006222.2      0.166597       -0.395149  0.180174   1.731872  8.329643e-02
RP4-669L17.10   0.004866       -0.008378  0.637626   0.326135  7.443221e-01
RP11-206L10.9   0.025799        0.025441  0.518434   1.124787  2.606792e-01
FAM87B          0.021720       -0.108609  0.526041   0.820357  4.120125e-01
...                  ...             ...       ...        ...           ...
MT-ND6          0.326766        0.048021  0.168365   2.594581  9.470641e-03
MT-CYB         27.295743       -0.407872  0.039216 -10.743383  6.366745e-27
AL592183.1      0.024681        0.008498  0.540244   0.920599  3.572598e-01
AC007325.4      0.038791       -0.268417  0.471655   1.113166  2.656372e-01
AC240274.1      0.088527       -1.325913  0.294415   0.592777  5.533304e-01

                       padj
FO538757.2     7.405836e-03
AP006222.2     1.295780e-01
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6         2.657545e-02
MT-CYB         9.038115e-26
AL592183.1              NaN
AC007325.4              NaN
AC240274.1     6.024862e-01

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Mo-mac
CELL TYPE:  Mo-mac ['Naive' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

... done in 0.23 seconds.

Fitting dispersions...
... done in 1.04 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.66 seconds.

Fitting LFCs...
... done in 1.21 seconds.

Calculating cook's distance...
... done in 0.81 seconds.

Replacing 37 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.02 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.62 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.078651       -0.008849  0.573281 -0.015435  9.876852e-01
AP006222.2      0.096044       -0.160000  0.423209 -0.378063  7.053837e-01
RP4-669L17.10   0.002334       -0.061650  4.069395 -0.015150  9.879128e-01
RP11-206L10.9   0.013983       -0.059766  1.708552 -0.034981  9.720952e-01
FAM87B          0.004783       -0.049076  3.525536 -0.013920  9.888938e-01
...                  ...             ...       ...       ...           ...
MT-ND6          0.170145       -0.114274  0.317844 -0.359528  7.192002e-01
MT-CYB         17.262874       -0.445057  0.060400 -7.368459  1.726114e-13
AL592183.1      0.016547       -0.030981  1.303419 -0.023769  9.810370e-01
AC007325.4      0.029348       -0.067875  0.914168 -0.074248  9.408132e-01
AC240274.1      0.043476       -0.307194  0.831938 -0.369251  7.119406e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6         8.975644e-01
MT-CYB         3.254713e-12
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13480 rows x 6 columns]

... done in 1.26 seconds.

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.08 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.078651        0.034969  0.483760 -0.015435  9.876852e-01
AP006222.2      0.096044       -0.081220  0.373420 -0.378063  7.053837e-01
RP4-669L17.10   0.002334       -0.007177  0.407993 -0.015150  9.879128e-01
RP11-206L10.9   0.013983       -0.005684  0.563581 -0.034981  9.720952e-01
FAM87B          0.004783        0.001542  0.724228 -0.013920  9.888938e-01
...                  ...             ...       ...       ...           ...
MT-ND6          0.170145       -0.092819  0.316938 -0.359528  7.192002e-01
MT-CYB         17.262874       -0.434418  0.061164 -7.368459  1.726114e-13
AL592183.1      0.016547        0.004591  0.620100 -0.023769  9.810370e-01
AC007325.4      0.029348       -0.023176  0.506287 -0.074248  9.408132e-01
AC240274.1      0.043476       -0.232251  0.566356 -0.369251  7.119406e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6         8.975644e-01
MT-CYB         3.254713e-12
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE DC
CELL TYPE:  DC ['Naive' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.68 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.14 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.23 seconds.

Replacing 40 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.48 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.105875       -0.505113  1.271440 -0.397276  6.911637e-01
AP006222.2      0.085837       -0.594642  1.247184 -0.476788  6.335134e-01
RP4-669L17.10   0.000000             NaN       NaN       NaN           NaN
RP11-206L10.9   0.038318       -0.445775  3.324471 -0.134089  8.933323e-01
FAM87B          0.013164       -0.656141  4.484539 -0.146312  8.836752e-01
...                  ...             ...       ...       ...           ...
MT-ND6          0.141704       -0.212681  0.919947 -0.231188  8.171687e-01
MT-CYB         15.573708       -1.008777  0.136593 -7.385263  1.521527e-13
AL592183.1      0.035953       -0.497494  2.333142 -0.213229  8.311481e-01
AC007325.4      0.031368       -0.611056  2.731740 -0.223687  8.230005e-01
AC240274.1      0.028429       -0.696753  2.513568 -0.277197  7.816291e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6                  NaN
MT-CYB         1.312214e-11
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13480 rows x 6 columns]

... done in 0.82 seconds.

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.105875       -0.015900  0.964522 -0.397276  6.911637e-01
AP006222.2      0.085837       -0.036345  0.891104 -0.476788  6.335134e-01
RP4-669L17.10   0.000000             NaN       NaN       NaN           NaN
RP11-206L10.9   0.038318        0.010651  2.451588 -0.134089  8.933323e-01
FAM87B          0.013164       -0.027684  0.647195 -0.146312  8.836752e-01
...                  ...             ...       ...       ...           ...
MT-ND6          0.141704        0.076302  0.987732 -0.231188  8.171687e-01
MT-CYB         15.573708       -0.976788  0.137783 -7.385263  1.521527e-13
AL592183.1      0.035953       -0.004758  1.172374 -0.213229  8.311481e-01
AC007325.4      0.031368       -0.035556  0.831348 -0.223687  8.230005e-01
AC240274.1      0.028429       -0.052012  0.764618 -0.277197  7.816291e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6                  NaN
MT-CYB         1.312214e-11
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE TRM
CELL TYPE:  TRM ['Naive' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

... done in 0.16 seconds.

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.51 seconds.

Replacing 13 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.56 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.090731        0.169967  0.575121  0.295532  0.767587
AP006222.2      0.095174       -0.083009  0.470956 -0.176257  0.860092
RP4-669L17.10   0.001011        0.078822  3.691247  0.021354  0.982963
RP11-206L10.9   0.023800        0.123692  1.482436  0.083439  0.933503
FAM87B          0.002466        0.068322  3.691167  0.018510  0.985232
...                  ...             ...       ...       ...       ...
MT-ND6          0.162161        0.024242  0.347939  0.069673  0.944454
MT-CYB         16.629375       -0.211518  0.056465 -3.745985  0.000180
AL592183.1      0.016972        0.117868  1.748485  0.067412  0.946254
AC007325.4      0.038648        0.035613  0.852269  0.041786  0.966669
AC240274.1      0.047795       -0.102844  0.849838 -0.121015  0.903679

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-ND6              NaN
MT-CYB         0.000816
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13480 rows x 6 columns]

... done in 1.08 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.090731        0.087552  0.493809  0.295532  0.767587
AP006222.2      0.095174       -0.134910  0.390708 -0.176257  0.860092
RP4-669L17.10   0.001011        0.002839  0.782859  0.021354  0.982963
RP11-206L10.9   0.023800        0.020223  0.692529  0.083439  0.933503
FAM87B          0.002466       -0.006757  0.413060  0.018510  0.985232
...                  ...             ...       ...       ...       ...
MT-ND6          0.162161       -0.030881  0.313400  0.069673  0.944454
MT-CYB         16.629375       -0.203160  0.056368 -3.745985  0.000180
AL592183.1      0.016972        0.018104  0.783359  0.067412  0.946254
AC007325.4      0.038648       -0.026032  0.449815  0.041786  0.966669
AC240274.1      0.047795       -0.111519  0.423197 -0.121015  0.903679

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-ND6              NaN
MT-CYB         0.000816
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Endothelial cells
CELL TYPE:  Endothelial cells ['Naive' 'Remission']

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.32 seconds.

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.83 seconds.

Fitting LFCs...
... done in 1.22 seconds.

Calculating cook's distance...
... done in 1.12 seconds.

Replacing 24 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.68 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
FO538757.2      0.092802        0.623925  0.345276   1.807034  7.075700e-02
AP006222.2      0.100325        0.376218  0.324018   1.161100  2.456012e-01
RP4-669L17.10   0.005730        0.516742  2.251358   0.229525  8.184611e-01
RP11-206L10.9   0.013193        0.522048  1.272607   0.410219  6.816450e-01
FAM87B          0.002063        0.514385  3.230173   0.159244  8.734768e-01
...                  ...             ...       ...        ...           ...
MT-ND6          0.139041        0.320369  0.254817   1.257251  2.086629e-01
MT-CYB         20.572515       -0.349802  0.032211 -10.859783  1.791753e-27
AL592183.1      0.035387        0.550306  0.629507   0.874186  3.820168e-01
AC007325.4      0.026627        0.448551  0.755858   0.593432  5.528919e-01
AC240274.1      0.015367        0.497294  1.046853   0.475037  6.347607e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6                  NaN
MT-CYB         8.070353e-26
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13480 rows x 6 columns]

... done in 1.26 seconds.

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.01 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
FO538757.2      0.092802        0.699901  0.436200   1.807034  7.075700e-02
AP006222.2      0.100325       -0.050146  0.280309   1.161100  2.456012e-01
RP4-669L17.10   0.005730       -0.001127  0.443019   0.229525  8.184611e-01
RP11-206L10.9   0.013193        0.007586  0.463475   0.410219  6.816450e-01
FAM87B          0.002063       -0.011016  0.335533   0.159244  8.734768e-01
...                  ...             ...       ...        ...           ...
MT-ND6          0.139041       -0.058983  0.238047   1.257251  2.086629e-01
MT-CYB         20.572515       -0.346698  0.032441 -10.859783  1.791753e-27
AL592183.1      0.035387        0.074995  0.456691   0.874186  3.820168e-01
AC007325.4      0.026627       -0.054137  0.376610   0.593432  5.528919e-01
AC240274.1      0.015367       -0.025262  0.399645   0.475037  6.347607e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6                  NaN
MT-CYB         8.070353e-26
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Epithelial cells
CELL TYPE:  Epithelial cells ['Naive' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.46 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.56 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 23 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.47 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.035398        0.082901  3.576426  0.023180  9.815068e-01
AP006222.2      0.122818       -0.315944  1.397616 -0.226059  8.211553e-01
RP4-669L17.10   0.000000             NaN       NaN       NaN           NaN
RP11-206L10.9   0.123623        0.278084  3.589030  0.077482  9.382403e-01
FAM87B          0.036602        0.544814  3.599808  0.151345  8.797033e-01
...                  ...             ...       ...       ...           ...
MT-ND6          0.360450        0.274014  1.462868  0.187312  8.514156e-01
MT-CYB         29.578334       -2.215624  0.340470 -6.507554  7.638411e-11
AL592183.1      0.000000             NaN       NaN       NaN           NaN
AC007325.4      0.011324        0.286239  3.589587  0.079741  9.364429e-01
AC240274.1      0.089743       -0.032627  3.378858 -0.009656  9.922956e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6                  NaN
MT-CYB         8.580482e-09
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13480 rows x 6 columns]

/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.13 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.035398   -2.475341e-07  0.001373  0.023180  9.815068e-01
AP006222.2      0.122818   -7.286677e-07  0.001725 -0.226059  8.211553e-01
RP4-669L17.10   0.000000             NaN       NaN       NaN           NaN
RP11-206L10.9   0.123623   -2.983714e-07  0.001469  0.077482  9.382403e-01
FAM87B          0.036602    1.151749e-07  0.004809  0.151345  8.797033e-01
...                  ...             ...       ...       ...           ...
MT-ND6          0.360450   -2.688097e-07  0.002307  0.187312  8.514156e-01
MT-CYB         29.578334   -2.367207e-05  0.001446 -6.507554  7.638411e-11
AL592183.1      0.000000             NaN       NaN       NaN           NaN
AC007325.4      0.011324   -5.715763e-08  0.001769  0.079741  9.364429e-01
AC240274.1      0.089743   -3.065589e-07  0.001412 -0.009656  9.922956e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-ND6                  NaN
MT-CYB         8.580482e-09
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE T cells
CELL TYPE:  T cells ['Naive' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.21 seconds.

Fitting dispersions...
... done in 1.10 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.98 seconds.

Calculating cook's distance...
... done in 0.75 seconds.

Replacing 50 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.02 seconds.

Fitting LFCs...
... done in 0.02 seconds.

Running Wald tests...
... done in 0.58 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.048638        0.768299  1.705011  0.450613  0.652269
AP006222.2      0.021647        0.702330  2.762047  0.254279  0.799280
RP4-669L17.10   0.001043        0.642200  8.008720  0.080188  0.936088
RP11-206L10.9   0.013847        0.669389  4.347744  0.153962  0.877639
FAM87B          0.000000             NaN       NaN       NaN       NaN
...                  ...             ...       ...       ...       ...
MT-ND6          0.173969        0.687684  0.726006  0.947216  0.343529
MT-CYB         10.891707        0.057448  0.113105  0.507919  0.611510
AL592183.1      0.017035        0.696537  2.962823  0.235092  0.814137
AC007325.4      0.013288        0.570046  3.370594  0.169123  0.865700
AC240274.1      0.006575        0.604197  5.656507  0.106815  0.914936

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-ND6              NaN
MT-CYB         0.759329
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13480 rows x 6 columns]

/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.41 seconds.

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.04 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.048638        0.012798  1.808792  0.450613  0.652269
AP006222.2      0.021647        0.004578  2.156104  0.254279  0.799280
RP4-669L17.10   0.001043       -0.000104  1.686792  0.080188  0.936088
RP11-206L10.9   0.013847        0.001664  2.595232  0.153962  0.877639
FAM87B          0.000000             NaN       NaN       NaN       NaN
...                  ...             ...       ...       ...       ...
MT-ND6          0.173969        0.035269  0.659248  0.947216  0.343529
MT-CYB         10.891707        0.039978  0.113197  0.507919  0.611510
AL592183.1      0.017035        0.003886  2.188341  0.235092  0.814137
AC007325.4      0.013288       -0.003053  0.665966  0.169123  0.865700
AC240274.1      0.006575       -0.002139  0.600264  0.106815  0.914936

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-ND6              NaN
MT-CYB         0.759329
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE ILC
CELL TYPE:  ILC ['Naive' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.55 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 0.74 seconds.

Fitting LFCs...
... done in 0.63 seconds.

Calculating cook's distance...
... done in 0.11 seconds.

Replacing 42 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.50 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2     0.067346        0.882693  2.921776  0.302109  0.762569
AP006222.2     0.029779        0.525002  5.191938  0.101119  0.919456
RP4-669L17.10  0.001691        0.695786  7.501008  0.092759  0.926095
RP11-206L10.9  0.024214        0.755498  5.754181  0.131296  0.895542
FAM87B         0.008585        0.705735  7.500988  0.094086  0.925041
...                 ...             ...       ...       ...       ...
MT-ND6         0.200938        0.728823  1.411851  0.516218  0.605702
MT-CYB         9.422380       -0.118560  0.245665 -0.482609  0.629374
AL592183.1     0.018121        0.745536  7.197647  0.103580  0.917502
AC007325.4     0.008711        0.725632  7.500950  0.096739  0.922934
AC240274.1     0.009557        0.715684  7.500969  0.095412  0.923987

                   padj
FO538757.2     0.998522
AP006222.2     0.998522
RP4-669L17.10  0.998522
RP11-206L10.9  0.998522
FAM87B         0.998522
...                 ...
MT-ND6         0.998522
MT-CYB         0.998522
AL592183.1     0.998522
AC007325.4     0.998522
AC240274.1     0.998522

[13480 rows x 6 columns]

/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 0.86 seconds.

/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7880211/ipykernel_3891478/1735980466.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.05 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2     0.067346        0.000968  0.858192  0.302109  0.762569
AP006222.2     0.029779       -0.000022  0.393901  0.101119  0.919456
RP4-669L17.10  0.001691       -0.000023  0.579998  0.092759  0.926095
RP11-206L10.9  0.024214        0.000183  1.045200  0.131296  0.895542
FAM87B         0.008585        0.000041  0.812127  0.094086  0.925041
...                 ...             ...       ...       ...       ...
MT-ND6         0.200938        0.002377  0.427511  0.516218  0.605702
MT-CYB         9.422380       -0.010571  0.212142 -0.482609  0.629374
AL592183.1     0.018121        0.000088  1.164846  0.103580  0.917502
AC007325.4     0.008711        0.000050  0.940353  0.096739  0.922934
AC240274.1     0.009557        0.000050  0.907897  0.095412  0.923987

                   padj
FO538757.2     0.998522
AP006222.2     0.998522
RP4-669L17.10  0.998522
RP11-206L10.9  0.998522
FAM87B         0.998522
...                 ...
MT-ND6         0.998522
MT-CYB         0.998522
AL592183.1     0.998522
AC007325.4     0.998522
AC240274.1     0.998522

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE B cells
CELL TYPE:  B cells ['Naive' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.60 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 0.73 seconds.

Fitting LFCs...
... done in 0.56 seconds.

Calculating cook's distance...
... done in 0.11 seconds.

Replacing 36 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.50 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Remission vs Naive
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.041138        0.872542  3.678055  0.237229  0.812479
AP006222.2      0.040580       -0.073222  3.286689 -0.022278  0.982226
RP4-669L17.10   0.002512        0.750927  7.673073  0.097865  0.922039
RP11-206L10.9   0.042904        0.594726  4.287071  0.138726  0.889667
FAM87B          0.001611        0.501153  7.663092  0.065398  0.947857
...                  ...             ...       ...       ...       ...
MT-ND6          0.155504        1.155516  1.849113  0.624903  0.532035
MT-CYB         11.053389       -0.554390  0.271014 -2.045612  0.040795
AL592183.1      0.032032        0.863356  4.151921  0.207941  0.835275
AC007325.4      0.002242        0.501153  7.663092  0.065398  0.947857
AC240274.1      0.018799        0.547845  7.498712  0.073059  0.941760

                   padj
FO538757.2     0.997145
AP006222.2     0.997304
RP4-669L17.10  0.997145
RP11-206L10.9  0.997145
FAM87B         0.997145
...                 ...
MT-ND6         0.997145
MT-CYB         0.997145
AL592183.1     0.997145
AC007325.4     0.997145
AC240274.1     0.997145

[13480 rows x 6 columns]
Shrunk log2 fold change & Wald test p-value: Group[T.Remission]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.041138        0.004182  2.401339  0.237229  0.812479
AP006222.2      0.040580       -0.016604  0.556619 -0.022278  0.982226
RP4-669L17.10   0.002512       -0.000110  1.629095  0.097865  0.922039
RP11-206L10.9   0.042904       -0.000068  1.026319  0.138726  0.889667
FAM87B          0.001611       -0.013706  0.301715  0.065398  0.947857
...                  ...             ...       ...       ...       ...
MT-ND6          0.155504        0.021904  1.807701  0.624903  0.532035
MT-CYB         11.053389       -0.325024  0.259042 -2.045612  0.040795
AL592183.1      0.032032        0.003156  2.580296  0.207941  0.835275
AC007325.4      0.002242       -0.014957  0.301231  0.065398  0.947857
AC240274.1      0.018799       -0.002458  0.682187  0.073059  0.941760

                   padj
FO538757.2     0.997145
AP006222.2     0.997304
RP4-669L17.10  0.997145
RP11-206L10.9  0.997145
FAM87B         0.997145
...                 ...
MT-ND6         0.997145
MT-CYB         0.997145
AL592183.1     0.997145
AC007325.4     0.997145
AC240274.1     0.997145

[13480 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Plasma cells
CELL TYPE:  Plasma cells ['Remission']





-------------------------------------------------------------------------------------

HERE Monocytes
CELL TYPE:  Monocytes ['Remission']





-------------------------------------------------------------------------------------

HERE Macrophages
CELL TYPE:  Macrophages ['Remission']





-------------------------------------------------------------------------------------

HERE Mast cells
CELL TYPE:  Mast cells ['Remission']





-------------------------------------------------------------------------------------

HERE Double-positive thymocytes
CELL TYPE:  Double-positive thymocytes ['Remission']

... done in 0.71 seconds.

In [8]:
# concat results across cell types
dea_df = pd.concat(dea_results)
dea_df = dea_df.reset_index().rename(columns={'level_0': groupby,'level_1':'index'}).set_index('index')
dea_df.head()

# Shrink LFCs
#stat_res.lfc_shrink(coeff='Group[T.Resistant]') # {condition_key}_cond_vs_ref
#stat_res.results_df

,cell_type,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
index,,,,,,,
FO538757.2,Fibroblasts,0.109863,0.373622,0.282069,3.064956,0.002177,0.007406
AP006222.2,Fibroblasts,0.166597,-0.395149,0.180174,1.731872,0.083296,0.129578
RP4-669L17.10,Fibroblasts,0.004866,-0.008378,0.637626,0.326135,0.744322,NaN
RP11-206L10.9,Fibroblasts,0.025799,0.025441,0.518434,1.124787,0.260679,NaN
FAM87B,Fibroblasts,0.021720,-0.108609,0.526041,0.820357,0.412013,NaN

In [9]:
# PyDeseq Seems to intrdoce NAs for some p-values
# NOTE: there sometimes some NaN being introduced, best to double check that, in this case it's only for a single gene, but it might be a problem.
len(dea_df[dea_df.isna().any(axis=1)])
dea_df.to_csv("deseq_results.csv")

In [10]:
#adata = adata[adata.obs[condition_key]=='Resistant'].copy()
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

In [11]:
lr_res = li.multi.df_to_lr(adata,
                           dea_df=dea_df,
                           resource_name='consensus', # NOTE: uses HUMAN gene symbols!
                           expr_prop=0.1, # calculated for adata as passed - used to filter interactions
                           groupby="cell_type",
                           stat_keys=['stat', 'pvalue', 'padj'],
                           use_raw=False,
                           complex_col='stat', # NOTE: we use the Wald Stat to deal with complexes
                           verbose=True,
                           return_all_lrs=False,
                           )
lr_res

Using resource `consensus`.
Using `.X`!
Converting to sparse csr matrix!
0.48 of entities in the resource are missing from the data.

,ligand,receptor,ligand_complex,receptor_complex,source,ligand_stat,ligand_pvalue,ligand_padj,ligand_expr,ligand_props,...,receptor_pvalue,receptor_padj,receptor_expr,receptor_props,interaction_stat,interaction_pvalue,interaction_padj,interaction_expr,interaction_props,interaction
0,HLA-A,APLP2,HLA-A,APLP2,B cells,2.403196,1.625248e-02,9.971451e-01,2.582359,0.915888,...,0.659240,0.997145,0.459724,0.252336,0.981117,0.337746,0.997145,1.521041,0.584112,HLA-A^APLP2
1,APP,CD74,APP,CD74,B cells,-0.507285,6.119547e-01,9.971451e-01,0.292029,0.171340,...,0.000003,0.004890,3.702399,0.819315,2.083583,0.305979,0.501017,1.997214,0.495327,APP^CD74
2,APP,LRP10,APP,LRP10,B cells,-0.507285,6.119547e-01,9.971451e-01,0.292029,0.171340,...,0.872032,0.997145,0.293962,0.193146,-0.173104,0.741994,0.997145,0.292995,0.182243,APP^LRP10
3,ICAM1,IL2RG,ICAM1,IL2RG,B cells,0.374066,7.083549e-01,9.971451e-01,0.162069,0.118380,...,0.084530,0.997145,0.571827,0.339564,1.049527,0.396442,0.997145,0.366948,0.228972,ICAM1^IL2RG
4,CD55,ADGRE5,CD55,ADGRE5,B cells,1.602468,1.090522e-01,9.971451e-01,1.249574,0.629283,...,0.448366,0.997145,0.237959,0.152648,1.180305,0.278709,0.997145,0.743766,0.390966,CD55^ADGRE5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15233,LGALS3,ENG,LGALS3,ENG,TRM,-12.216826,2.527610e-34,1.260710e-32,1.782732,0.881233,...,0.793968,0.872703,0.628836,0.502267,-5.977833,0.396984,0.436351,1.205784,0.691750,LGALS3^ENG
15234,CD59,STAB1,CD59,STAB1,TRM,-1.988369,4.677087e-02,1.118474e-01,1.036731,0.680870,...,0.095819,0.197454,0.765055,0.517679,-1.826921,0.071295,0.154651,0.900893,0.599275,CD59^STAB1
15235,TGFB1,LPP,TGFB1,LPP,TRM,-0.748420,4.542070e-01,6.106061e-01,0.364873,0.326383,...,0.379309,NaN,0.178764,0.165005,-0.813795,0.416758,0.610606,0.271818,0.245694,TGFB1^LPP
15236,ENTPD1,TMIGD3,ENTPD1,TMIGD3,TRM,-1.354551,1.755607e-01,NaN,0.182981,0.170444,...,0.380733,0.543522,0.190640,0.153218,-0.239002,0.278147,0.543522,0.186810,0.161831,ENTPD1^TMIGD3
15237,MAML2,NOTCH2,MAML2,NOTCH2,TRM,0.031824,9.746126e-01,NaN,0.127705,0.122393,...,0.729693,NaN,0.136760,0.131460,0.188679,0.852153,NaN,0.132233,0.126927,MAML2^NOTCH2

In [12]:
lr_res["target"].value_counts()

target
DC                   2090
Fibroblasts          1989
Mo-mac               1951
TRM                  1929
Endothelial cells    1695
Epithelial cells     1582
ILC                  1119
T cells              1094
B cells               746
Name: count, dtype: int64

In [13]:
lr_res = lr_res.sort_values("interaction_stat", ascending=False, key=abs)
# Select all of the interactions with macrophages are the target
lr_res = lr_res[lr_res["target"] == "Mo-mac"]
lr_res.head(10)

,ligand,receptor,ligand_complex,receptor_complex,source,ligand_stat,ligand_pvalue,ligand_padj,ligand_expr,ligand_props,...,receptor_pvalue,receptor_padj,receptor_expr,receptor_props,interaction_stat,interaction_pvalue,interaction_padj,interaction_expr,interaction_props,interaction
8696,CXCL12,CXCR4,CXCL12,CXCR4,Fibroblasts,24.866248,1.725497e-136,4.601529e-134,1.925483,0.690286,...,5.335631e-26,2.696272e-24,0.999279,0.558082,17.705814,2.667815e-26,1.348136e-24,1.462381,0.624184,CXCL12^CXCR4
14807,FN1,PLAUR,FN1,PLAUR,TRM,18.905836,1.021077e-79,2.495511e-77,2.580193,0.877607,...,8.110387e-30,5.039076e-28,1.541877,0.775046,15.124005,4.055193e-30,2.519538e-28,2.061035,0.826326,FN1^PLAUR
8827,PKM,CD44,PKM,CD44,Fibroblasts,-27.899959,2.671131e-171,1.662111e-168,1.519595,0.822000,...,4.977315e-02,1.517621e-01,1.488237,0.837124,-14.930934,2.488658e-02,7.588103e-02,1.503916,0.829562,PKM^CD44
8733,ANGPTL2,ITGA5,ANGPTL2,ITGA5_ITGB1,Fibroblasts,-26.871359,4.748541e-159,2.363823e-156,1.060468,0.686286,...,9.581384e-02,2.521767e-01,0.199692,0.194837,-14.268427,4.790692e-02,1.260884e-01,0.630080,0.440561,ANGPTL2^ITGA5_ITGB1
8830,CALM1,PTPRA,CALM1,PTPRA,Fibroblasts,-26.498600,1.005911e-154,4.172854e-152,1.532840,0.840857,...,1.230686e-01,3.062573e-01,0.203277,0.189305,-14.020310,6.153429e-02,1.531287e-01,0.868058,0.515081,CALM1^PTPRA
8764,TIMP2,ITGB1,TIMP2,ITGB1,Fibroblasts,-22.272416,6.841170e-110,8.807416e-108,1.245770,0.784000,...,1.314167e-08,1.469231e-07,0.559787,0.454825,-13.978314,6.570836e-09,7.346156e-08,0.902779,0.619412,TIMP2^ITGB1
8735,ANGPTL2,TLR4,ANGPTL2,TLR4,Fibroblasts,-26.871359,4.748541e-159,2.363823e-156,1.060468,0.686286,...,3.410301e-01,6.225935e-01,0.180797,0.171481,-13.911745,1.705151e-01,3.112967e-01,0.620633,0.428883,ANGPTL2^TLR4
12901,HLA-B,LILRB1,HLA-B,LILRB1,Mo-mac,26.866766,5.373110e-159,2.036409e-155,2.855927,0.979717,...,6.732635e-01,8.779539e-01,0.159789,0.151813,13.644220,3.366317e-01,4.389769e-01,1.507858,0.565765,HLA-B^LILRB1
8737,ANGPTL2,LILRB2,ANGPTL2,LILRB2,Fibroblasts,-26.871359,4.748541e-159,2.363823e-156,1.060468,0.686286,...,7.653047e-01,9.199191e-01,0.255341,0.236017,-13.584940,3.826524e-01,4.599595e-01,0.657905,0.461151,ANGPTL2^LILRB2
12900,HLA-B,LILRB2,HLA-B,LILRB2,Mo-mac,26.866766,5.373110e-159,2.036409e-155,2.855927,0.979717,...,7.653047e-01,9.199191e-01,0.255341,0.236017,13.284122,3.826524e-01,4.599595e-01,1.555634,0.607867,HLA-B^LILRB2

In [14]:
lr_res.to_csv(output_fname, index=False)