# Perform differential expression analysis between RA patients

**Author: Caroline Larkin**

**Research Group: Gottschalk Lab, Department of Immunology, University of Pittsburgh**

Notebook based on [link](https://liana-py.readthedocs.io/en/latest/notebooks/targeted.html)

In [1]:
import numpy as np
import pandas as pd
import anndata as ad 
import scanpy as sc

import celltypist
from celltypist import models

import liana as li

# Import DESeq2
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats

import matplotlib.pyplot as plt
import seaborn as sns 

#sample_ids = ["SA149P", "SA154", "SA220", "SA222", "SA227", "SA159", "SA168", "SA225"]
#sample_labels = ["UPA", "UPA", "Naive", "Resistant", "Resistant", "Remission", "Remission", "Remission"] 

sample_ids = ["SA222", "SA227", "SA159", "SA168", "SA225"]
sample_labels = ["Resistant", "Resistant", "Remission", "Remission", "Remission"] 
CONTROL_GROUP = "Remission"
TEST_GROUP = "Resistant"
TARGET_CELL = "TRM"

output_fname = f"../Data/DECCC_{TEST_GROUP}_v_{CONTROL_GROUP}_{TARGET_CELL}-targets.csv"
data_dir = "../Data/EMATB8322/"

# Download base models from celltypist
models.download_models()

/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/celltypist/classifier.py:11: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  from scanpy import __version__ as scv
📂 Storing models in /ihome/rgottschalk/cil8/.celltypist/data/models
⏩ Skipping [1/60]: Immune_All_Low.pkl (file exists)
⏩ Skipping [2/60]: Immune_All_High.pkl (file exists)
⏩ Skipping [3/60]: Adult_COVID19_PBMC.pkl (file exists)
⏩ Skipping [4/60]: Adult_CynomolgusMacaque_Hippocampus.pkl (file exists)
⏩ Skipping [5/60]: Adult_Human_MTG.pkl (file exists)
⏩ Skipping [6/60]: Adult_Human_PancreaticIslet.pkl (file exists)
⏩ Skipping [7/60]: Adult_Human_PrefrontalCortex.pkl (file exists)
⏩ Skipping [8/60]: Adult_Human_Skin.pkl (file exists)
⏩ Skipping [9/60]: Adult_Human_Vascular.pkl (file exists)
⏩ Skipping [10/60]: Adult_Mouse_Gut.pkl (file exists)
⏩ Skipping [11/60]: Adult_Mouse_OlfactoryBulb.pkl (file exists)
⏩ Skipping [12/60]: Adult_Pig_Hippocampus.pkl (file exists)
⏩ Skipping [13/60]: Adult_RhesusMacaque_Hippocampus.pkl (file exists)
⏩ Skipping [14/60]: Adult_cHSPCs_Illumina.pkl (file exists)
⏩ Skipping [15/60]: Adult_cHSPCs_Ultima.pkl (file exists)
⏩ Skipping [16/60]: Autopsy_COVID19_Lung.pkl (file exists)
⏩ Skipping [17/60]: COVID19_HumanChallenge_Blood.pkl (file exists)
⏩ Skipping [18/60]: COVID19_Immune_Landscape.pkl (file exists)
⏩ Skipping [19/60]: Cells_Adult_Breast.pkl (file exists)
⏩ Skipping [20/60]: Cells_Fetal_Lung.pkl (file exists)
⏩ Skipping [21/60]: Cells_Human_Tonsil.pkl (file exists)
⏩ Skipping [22/60]: Cells_Intestinal_Tract.pkl (file exists)
⏩ Skipping [23/60]: Cells_Lung_Airway.pkl (file exists)
⏩ Skipping [24/60]: Developing_Human_Brain.pkl (file exists)
⏩ Skipping [25/60]: Developing_Human_Gonads.pkl (file exists)
⏩ Skipping [26/60]: Developing_Human_Hippocampus.pkl (file exists)
⏩ Skipping [27/60]: Developing_Human_Organs.pkl (file exists)
⏩ Skipping [28/60]: Developing_Human_Thymus.pkl (file exists)
⏩ Skipping [29/60]: Developing_Mouse_Brain.pkl (file exists)
⏩ Skipping [30/60]: Developing_Mouse_Hippocampus.pkl (file exists)
⏩ Skipping [31/60]: Fetal_Human_AdrenalGlands.pkl (file exists)
⏩ Skipping [32/60]: Fetal_Human_Pancreas.pkl (file exists)
⏩ Skipping [33/60]: Fetal_Human_Pituitary.pkl (file exists)
⏩ Skipping [34/60]: Fetal_Human_Retina.pkl (file exists)
⏩ Skipping [35/60]: Fetal_Human_Skin.pkl (file exists)
⏩ Skipping [36/60]: Healthy_Adult_Heart.pkl (file exists)
⏩ Skipping [37/60]: Healthy_COVID19_PBMC.pkl (file exists)
⏩ Skipping [38/60]: Healthy_Human_Liver.pkl (file exists)
⏩ Skipping [39/60]: Healthy_Mouse_Liver.pkl (file exists)
⏩ Skipping [40/60]: Human_AdultAged_Hippocampus.pkl (file exists)
⏩ Skipping [41/60]: Human_Colorectal_Cancer.pkl (file exists)
⏩ Skipping [42/60]: Human_Developmental_Retina.pkl (file exists)
⏩ Skipping [43/60]: Human_Embryonic_YolkSac.pkl (file exists)
⏩ Skipping [44/60]: Human_Endometrium_Atlas.pkl (file exists)
⏩ Skipping [45/60]: Human_IPF_Lung.pkl (file exists)
⏩ Skipping [46/60]: Human_Longitudinal_Hippocampus.pkl (file exists)
⏩ Skipping [47/60]: Human_Lung_Atlas.pkl (file exists)
⏩ Skipping [48/60]: Human_PF_Lung.pkl (file exists)
⏩ Skipping [49/60]: Human_Placenta_Decidua.pkl (file exists)
⏩ Skipping [50/60]: Lethal_COVID19_Lung.pkl (file exists)
⏩ Skipping [51/60]: Mouse_Dendritic_Subtypes.pkl (file exists)
⏩ Skipping [52/60]: Mouse_Dentate_Gyrus.pkl (file exists)
⏩ Skipping [53/60]: Mouse_Isocortex_Hippocampus.pkl (file exists)
⏩ Skipping [54/60]: Mouse_Postnatal_DentateGyrus.pkl (file exists)
⏩ Skipping [55/60]: Mouse_Whole_Brain.pkl (file exists)
⏩ Skipping [56/60]: Nuclei_Human_InnerEar.pkl (file exists)
⏩ Skipping [57/60]: Nuclei_Lung_Airway.pkl (file exists)
⏩ Skipping [58/60]: PaediatricAdult_COVID19_Airway.pkl (file exists)
⏩ Skipping [59/60]: PaediatricAdult_COVID19_PBMC.pkl (file exists)
⏩ Skipping [60/60]: Pan_Fetal_Human.pkl (file exists)

## 1. Load data

In [2]:
# Load celltypist immune model
model = models.Model.load(model = "Immune_All_High.pkl")

mac_subtype_df = pd.read_csv("../Data/macrophage_subtype_designation.csv", index_col=0)
mac_subtype_df

     Mac Subtype      Group Sample             Barcode
0         Mo-mac      Naive  SA220  AAACCTGCACCCATGG-1
1            TRM      Naive  SA220  AAACGGGTCAACGAAA-1
2            TRM      Naive  SA220  AAAGCAAAGTAAGTAC-1
3         Mo-mac      Naive  SA220  AAATGCCGTCCCTTGT-1
4            TRM      Naive  SA220  AACCATGTCTTGGGTA-1
...          ...        ...    ...                 ...
4712      Mo-mac  Remission  SA225  TGGGAAGAGAGTACAT-1
4713         TRM  Remission  SA225  TGGGCGTGTCACACGC-1
4714      Mo-mac  Remission  SA225  TTAGTTCTCTGTTGAG-1
4715      Mo-mac  Remission  SA225  TTATGCTCAACACGCC-1
4716      Mo-mac  Remission  SA225  TTGGAACAGGTGTGGT-1

[4717 rows x 4 columns]

In [3]:
ads = []
for id, label in zip(sample_ids, sample_labels):
    cur_ad = sc.read_mtx(filename=f"{data_dir}{id}/processed_counts.mtx").transpose()
    gene_names = pd.read_csv(f"{data_dir}{id}/processed_gene_names.csv", header=None)
    cur_ad.var_names = gene_names.values.flatten()
    print()#print(gene_names.values.flatten())
    barcodes = pd.read_csv(f"{data_dir}{id}/processed_metadata.csv", usecols=["barcode"])
    cur_ad.obs_names = barcodes.values.flatten()
    cur_ad.obs_names_make_unique()
    cur_ad.obs["Group"] = [label]* len(barcodes)
    cur_ad.obs["Sample"] = [id] * len(barcodes)
    display(cur_ad)

    # create a temporary copy of adata to preprocess
    temp = cur_ad.copy()
    # Normalizing to median total counts
    sc.pp.normalize_total(temp, target_sum=10000)
    # Logarithmize the data
    sc.pp.log1p(temp)

    predictions = celltypist.annotate(temp, model=model)
    new_ad = predictions.to_adata();
    cur_ad.obs["cell_type"] = new_ad.obs["predicted_labels"]
    cell_counts = cur_ad.obs["cell_type"].value_counts()
    # removing cell types with low counts
    #print(cell_counts)
    keep_cell_types = cell_counts[cell_counts.values > 10]
    #print(keep_cell_types.index.values)
    cur_ad = cur_ad[cur_ad.obs["cell_type"].isin(keep_cell_types.index.values)]
    display(cur_ad)
    #break
    ads.append(cur_ad); 
    del temp
    del new_ad

AnnData object with n_obs × n_vars = 5189 × 17673
    obs: 'Group', 'Sample'

🔬 Input data has 5189 cells and 17673 genes
🔗 Matching reference genes in the model
🧬 5000 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 5173 × 17673
    obs: 'Group', 'Sample', 'cell_type'

AnnData object with n_obs × n_vars = 4774 × 16896
    obs: 'Group', 'Sample'

🔬 Input data has 4774 cells and 16896 genes
🔗 Matching reference genes in the model
🧬 4930 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 4757 × 16896
    obs: 'Group', 'Sample', 'cell_type'

AnnData object with n_obs × n_vars = 3206 × 16155
    obs: 'Group', 'Sample'

🔬 Input data has 3206 cells and 16155 genes
🔗 Matching reference genes in the model
🧬 4850 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 3195 × 16155
    obs: 'Group', 'Sample', 'cell_type'

AnnData object with n_obs × n_vars = 5058 × 17498
    obs: 'Group', 'Sample'

🔬 Input data has 5058 cells and 17498 genes
🔗 Matching reference genes in the model
🧬 5011 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 5042 × 17498
    obs: 'Group', 'Sample', 'cell_type'

AnnData object with n_obs × n_vars = 1783 × 13829
    obs: 'Group', 'Sample'

🔬 Input data has 1783 cells and 13829 genes
🔗 Matching reference genes in the model
🧬 4345 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!

View of AnnData object with n_obs × n_vars = 1765 × 13829
    obs: 'Group', 'Sample', 'cell_type'

In [4]:
adata = sc.concat(ads, merge="same", join="inner")
adata.obs_names_make_unique()
#adata.X.dtype = np.int64
adata.X = adata.X.toarray()
adata.X[np.isnan(adata.X)] = 0 
display(adata)

AnnData object with n_obs × n_vars = 19932 × 13566
    obs: 'Group', 'Sample', 'cell_type'

In [5]:
# Overwrite the macrophages with the specific subtype from the dataframe file
mac_mask = adata.obs["cell_type"] == "Macrophages"
df_mac = (
    mac_subtype_df.set_index(["Barcode", "Sample"])
      .loc[:, "Mac Subtype"])
print(df_mac)

adata_index = pd.MultiIndex.from_arrays(
    [adata.obs_names, adata.obs["Sample"]],
    names=["Barcode", "Sample"]
)
print(adata_index)

# Create a Series aligned to AnnData
mac_subtypes = df_mac.reindex(adata_index)
print(mac_subtypes.notna())
print("-----------")
print(mac_mask)

new_categories = mac_subtypes.dropna().unique()

adata.obs["cell_type"] = adata.obs["cell_type"].cat.add_categories(new_categories)

overwrite_mask = (
    mac_mask.to_numpy() &
    mac_subtypes.notna().to_numpy()
)

adata.obs.loc[overwrite_mask, "cell_type"] = mac_subtypes.to_numpy()[overwrite_mask]
adata.obs["cell_type"].value_counts()

Barcode             Sample
AAACCTGCACCCATGG-1  SA220     Mo-mac
AAACGGGTCAACGAAA-1  SA220        TRM
AAAGCAAAGTAAGTAC-1  SA220        TRM
AAATGCCGTCCCTTGT-1  SA220     Mo-mac
AACCATGTCTTGGGTA-1  SA220        TRM
                               ...
TGGGAAGAGAGTACAT-1  SA225     Mo-mac
TGGGCGTGTCACACGC-1  SA225        TRM
TTAGTTCTCTGTTGAG-1  SA225     Mo-mac
TTATGCTCAACACGCC-1  SA225     Mo-mac
TTGGAACAGGTGTGGT-1  SA225     Mo-mac
Name: Mac Subtype, Length: 4717, dtype: object
MultiIndex([('AAACCTGAGAGCCTAG-1', 'SA222'),
            ('AAACCTGAGAGGTTAT-1', 'SA222'),
            ('AAACCTGAGCTGCAAG-1', 'SA222'),
            ('AAACCTGAGGCCCTCA-1', 'SA222'),
            ('AAACCTGAGTACATGA-1', 'SA222'),
            ('AAACCTGAGTGACTCT-1', 'SA222'),
            ('AAACCTGCAATAGAGT-1', 'SA222'),
            ('AAACCTGCAATGTTGC-1', 'SA222'),
            ('AAACCTGCACGAGGTA-1', 'SA222'),
            ('AAACCTGCAGTGAGTG-1', 'SA222'),
            ...
            ('TTTCCTCCAGTATAAG-1', 'SA225'),
            ('TTTGCGCAGAATGTTG-1', 'SA225'),
            ('TTTGCGCCAGTTTACG-1', 'SA225'),
            ('TTTGCGCGTGAAAGAG-1', 'SA225'),
            ('TTTGGTTAGATGCCTT-1', 'SA225'),
            ('TTTGGTTAGCAAATCA-1', 'SA225'),
            ('TTTGGTTAGTGTCTCA-1', 'SA225'),
            ('TTTGGTTCACGCTTTC-1', 'SA225'),
            ('TTTGGTTTCAGGCGAA-1', 'SA225'),
            ('TTTGGTTTCATGCATG-1', 'SA225')],
           names=['Barcode', 'Sample'], length=19932)
Barcode             Sample
AAACCTGAGAGCCTAG-1  SA222     False
AAACCTGAGAGGTTAT-1  SA222      True
AAACCTGAGCTGCAAG-1  SA222     False
AAACCTGAGGCCCTCA-1  SA222     False
AAACCTGAGTACATGA-1  SA222      True
                              ...
TTTGGTTAGCAAATCA-1  SA225     False
TTTGGTTAGTGTCTCA-1  SA225     False
TTTGGTTCACGCTTTC-1  SA225     False
TTTGGTTTCAGGCGAA-1  SA225     False
TTTGGTTTCATGCATG-1  SA225     False
Name: Mac Subtype, Length: 19932, dtype: bool
-----------
AAACCTGAGAGCCTAG-1    False
AAACCTGAGAGGTTAT-1     True
AAACCTGAGCTGCAAG-1    False
AAACCTGAGGCCCTCA-1    False
AAACCTGAGTACATGA-1     True
                      ...
TTTGGTTAGCAAATCA-1    False
TTTGGTTAGTGTCTCA-1    False
TTTGGTTCACGCTTTC-1    False
TTTGGTTTCAGGCGAA-1    False
TTTGGTTTCATGCATG-1    False
Name: cell_type, Length: 19932, dtype: bool

cell_type
Fibroblasts                   7248
Endothelial cells             3362
Mo-mac                        2475
T cells                       2162
TRM                           1734
DC                             810
Monocytes                      505
B cells                        501
ILC                            418
Plasma cells                   389
Mast cells                     121
Epithelial cells               112
Macrophages                     58
pDC                             24
Double-positive thymocytes      13
Name: count, dtype: int64

In [6]:
sets = [set(x.var_names) for x in ads]
union = list(sets[0].intersection(*sets[1:]))
print("The total number of genes included in these samples is: ", len(union))

The total number of genes included in these samples is:  13566

In [7]:
condition_key = "Group"
groupby = "cell_type"
dea_results = {}
quiet = True

for cell_group in adata.obs[groupby].unique():
    # Select cell profiles
    ctdata = adata[adata.obs[groupby] == cell_group].copy()
    print("\n\n\n\n\n-------------------------------------------------------------------------------------\n\nHERE", cell_group); 
    print("CELL TYPE: ", cell_group, ctdata.obs["Group"].unique())

    # Check to see if cell type is present in both Groups
    if(len(np.unique(ctdata.obs["Group"])) < 2):
        # remove it from the dataset and continue 
        adata = adata[adata.obs[groupby] != cell_group]
        continue
        
    # Build DESeq2 object
    # NOTE: this data is actually paired, so one could consider fitting the patient label as a confounder
    dds = DeseqDataSet(
    	adata=ctdata,
    	design_factors=condition_key,
    	ref_level=[condition_key, CONTROL_GROUP], # set control as reference
    	refit_cooks=True,
    )

    # Compute LFCs
    dds.deseq2()
    # Contrast between stim and ctrl
    stat_res = DeseqStats(dds, contrast=[condition_key, TEST_GROUP, CONTROL_GROUP])
    # Compute Wald test
    stat_res.summary()
    # Shrink LFCs
    stat_res.lfc_shrink(coeff=f"Group[T.{TEST_GROUP}]") # {condition_key}_cond_vs_ref
    #stat_res.lfc_shrink(coeff='condition_Resistant_vs_Naive') # {condition_key}_cond_vs_ref

    dea_results[cell_group] = stat_res.results_df;

-------------------------------------------------------------------------------------

HERE Fibroblasts
CELL TYPE:  Fibroblasts ['Resistant' 'Remission']

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 2.44 seconds.

Fitting dispersions...
... done in 8.76 seconds.

Fitting dispersion trend curve...
... done in 0.24 seconds.

Fitting MAP dispersions...
... done in 8.23 seconds.

Fitting LFCs...
... done in 7.57 seconds.

Calculating cook's distance...
... done in 6.66 seconds.

Replacing 11 outlier genes.

Fitting dispersions...
... done in 0.02 seconds.

Fitting MAP dispersions...
... done in 0.03 seconds.

Fitting LFCs...
... done in 0.04 seconds.

Running Wald tests...
... done in 2.89 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.131050       -0.379484  0.141461 -2.682612  7.304968e-03
AP006222.2      0.187213       -0.327191  0.112485 -2.908755  3.628706e-03
RP4-669L17.10   0.006052       -0.373616  1.284845 -0.290787  7.712141e-01
RP11-206L10.9   0.027362       -0.371771  0.388648 -0.956574  3.387823e-01
FAM87B          0.010532       -0.397049  0.669742 -0.592839  5.532890e-01
...                  ...             ...       ...       ...           ...
MT-CYB         25.645617       -0.199566  0.023968 -8.326287  8.341764e-17
AC145212.2      0.009277       -0.361301  0.896429 -0.403045  6.869155e-01
AL592183.1      0.032059       -0.361271  0.428679 -0.842754  3.993660e-01
AC007325.4      0.034990       -0.380325  0.370564 -1.026342  3.047302e-01
AC240274.1      0.119039       -0.166446  0.154110 -1.080047  2.801211e-01

                       padj
FO538757.2     1.234356e-02
AP006222.2     6.663413e-03
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-CYB         6.814858e-16
AC145212.2              NaN
AL592183.1              NaN
AC007325.4              NaN
AC240274.1     2.897990e-01

[13566 rows x 6 columns]

... done in 5.72 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.131050       -0.091905  0.159709 -2.682612  7.304968e-03
AP006222.2      0.187213        0.009762  0.128138 -2.908755  3.628706e-03
RP4-669L17.10   0.006052       -0.013115  0.418037 -0.290787  7.712141e-01
RP11-206L10.9   0.027362       -0.007938  0.322249 -0.956574  3.387823e-01
FAM87B          0.010532       -0.158460  0.416020 -0.592839  5.532890e-01
...                  ...             ...       ...       ...           ...
MT-CYB         25.645617       -0.198317  0.024559 -8.326287  8.341764e-17
AC145212.2      0.009277        0.066233  0.500705 -0.403045  6.869155e-01
AL592183.1      0.032059        0.012309  0.341476 -0.842754  3.993660e-01
AC007325.4      0.034990       -0.075465  0.314874 -1.026342  3.047302e-01
AC240274.1      0.119039        0.863017  0.191766 -1.080047  2.801211e-01

                       padj
FO538757.2     1.234356e-02
AP006222.2     6.663413e-03
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-CYB         6.814858e-16
AC145212.2              NaN
AL592183.1              NaN
AC007325.4              NaN
AC240274.1     2.897990e-01

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE TRM
CELL TYPE:  TRM ['Resistant' 'Remission']

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.57 seconds.

Fitting dispersions...
... done in 2.14 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 3.09 seconds.

Fitting LFCs...
... done in 2.18 seconds.

Calculating cook's distance...
... done in 1.54 seconds.

Replacing 30 outlier genes.

Fitting dispersions...
... done in 0.02 seconds.

Fitting MAP dispersions...
... done in 0.02 seconds.

Fitting LFCs...
... done in 0.02 seconds.

Running Wald tests...
... done in 1.20 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
FO538757.2      0.092276        0.493115  0.353592   1.394589  1.631398e-01
AP006222.2      0.116276        0.662546  0.272372   2.432503  1.499487e-02
RP4-669L17.10   0.000534        0.517863  2.891419   0.179103  8.578566e-01
RP11-206L10.9   0.018306        0.482791  1.009943   0.478037  6.326236e-01
FAM87B          0.000565        0.515385  2.891414   0.178247  8.585292e-01
...                  ...             ...       ...        ...           ...
MT-CYB         17.860630        0.623984  0.044095  14.150921  1.843263e-45
AC145212.2      0.003565        0.514933  2.891386   0.178092  8.586507e-01
AL592183.1      0.024062        0.559641  0.854094   0.655245  5.123099e-01
AC007325.4      0.032040        0.484384  0.642504   0.753900  4.509091e-01
AC240274.1      0.042685        0.546249  0.607820   0.898701  3.688119e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-CYB         2.866273e-43
AC145212.2              NaN
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13566 rows x 6 columns]

... done in 2.18 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
FO538757.2      0.092276        0.065863  0.287343   1.394589  1.631398e-01
AP006222.2      0.116276        0.928745  0.324770   2.432503  1.499487e-02
RP4-669L17.10   0.000534       -0.012068  0.316576   0.179103  8.578566e-01
RP11-206L10.9   0.018306       -0.046414  0.341849   0.478037  6.326236e-01
FAM87B          0.000565       -0.013335  0.307806   0.178247  8.585292e-01
...                  ...             ...       ...        ...           ...
MT-CYB         17.860630        0.619371  0.044739  14.150921  1.843263e-45
AC145212.2      0.003565       -0.009969  0.332354   0.178092  8.586507e-01
AL592183.1      0.024062        0.069057  0.411419   0.655245  5.123099e-01
AC007325.4      0.032040        0.025358  0.341038   0.753900  4.509091e-01
AC240274.1      0.042685        0.143197  0.412125   0.898701  3.688119e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-CYB         2.866273e-43
AC145212.2              NaN
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Mo-mac
CELL TYPE:  Mo-mac ['Resistant' 'Remission']

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.83 seconds.

Fitting dispersions...
... done in 3.50 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 4.14 seconds.

Fitting LFCs...
... done in 2.84 seconds.

Calculating cook's distance...
... done in 2.22 seconds.

Replacing 32 outlier genes.

Fitting dispersions...
... done in 0.02 seconds.

Fitting MAP dispersions...
... done in 0.02 seconds.

Fitting LFCs...
... done in 0.02 seconds.

Running Wald tests...
... done in 1.35 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
FO538757.2      0.091885        0.359154  0.309630   1.159945  2.460710e-01
AP006222.2      0.113605        0.363914  0.247563   1.469984  1.415662e-01
RP4-669L17.10   0.003488        0.318794  2.905139   0.109734  9.126200e-01
RP11-206L10.9   0.014642        0.309338  1.113607   0.277780  7.811811e-01
FAM87B          0.005736        0.314052  2.108288   0.148961  8.815846e-01
...                  ...             ...       ...        ...           ...
MT-CYB         19.589052        0.450386  0.042807  10.521227  6.896931e-26
AC145212.2      0.006154        0.314518  1.461366   0.215222  8.295942e-01
AL592183.1      0.022518        0.359121  0.661372   0.542994  5.871338e-01
AC007325.4      0.030274        0.314675  0.550886   0.571216  5.678533e-01
AC240274.1      0.039971        0.357219  0.532979   0.670231  5.027103e-01

                       padj
FO538757.2     8.980894e-01
AP006222.2     6.790556e-01
RP4-669L17.10  9.234078e-01
RP11-206L10.9  9.234078e-01
FAM87B         9.234078e-01
...                     ...
MT-CYB         1.084422e-23
AC145212.2     9.234078e-01
AL592183.1     9.234078e-01
AC007325.4     9.234078e-01
AC240274.1     9.234078e-01

[13566 rows x 6 columns]

... done in 2.72 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
FO538757.2      0.091885        0.130944  0.267381   1.159945  2.460710e-01
AP006222.2      0.113605        0.288697  0.280625   1.469984  1.415662e-01
RP4-669L17.10   0.003488        0.003190  0.336888   0.109734  9.126200e-01
RP11-206L10.9   0.014642        0.009575  0.297956   0.277780  7.811811e-01
FAM87B          0.005736       -0.007444  0.275582   0.148961  8.815846e-01
...                  ...             ...       ...        ...           ...
MT-CYB         19.589052        0.444679  0.043870  10.521227  6.896931e-26
AC145212.2      0.006154        0.003459  0.298834   0.215222  8.295942e-01
AL592183.1      0.022518        0.086184  0.335649   0.542994  5.871338e-01
AC007325.4      0.030274        0.045182  0.281877   0.571216  5.678533e-01
AC240274.1      0.039971        0.123223  0.342308   0.670231  5.027103e-01

                       padj
FO538757.2     8.980894e-01
AP006222.2     6.790556e-01
RP4-669L17.10  9.234078e-01
RP11-206L10.9  9.234078e-01
FAM87B         9.234078e-01
...                     ...
MT-CYB         1.084422e-23
AC145212.2     9.234078e-01
AL592183.1     9.234078e-01
AC007325.4     9.234078e-01
AC240274.1     9.234078e-01

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE ILC
CELL TYPE:  ILC ['Resistant' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.13 seconds.

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.22 seconds.

Fitting MAP dispersions...
... done in 1.69 seconds.

Fitting LFCs...
... done in 1.31 seconds.

Calculating cook's distance...
... done in 0.34 seconds.

Replacing 16 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.90 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.066339       -0.369848  1.016286 -0.363921  0.715917
AP006222.2      0.031489       -0.305725  1.728611 -0.176861  0.859617
RP4-669L17.10   0.001947       -0.358899  3.174465 -0.113058  0.909984
RP11-206L10.9   0.026068       -0.324173  1.847730 -0.175444  0.860731
FAM87B          0.006367       -0.368814  3.174420 -0.116183  0.907507
...                  ...             ...       ...       ...       ...
MT-CYB         10.676399        0.329504  0.085200  3.867410  0.000110
AC145212.2      0.002041       -0.358899  3.174465 -0.113058  0.909984
AL592183.1      0.031330       -0.260807  1.829075 -0.142590  0.886614
AC007325.4      0.013531       -0.323158  2.575768 -0.125461  0.900159
AC240274.1      0.025493       -0.205887  2.261486 -0.091041  0.927460

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-CYB         0.001138
AC145212.2          NaN
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13566 rows x 6 columns]

... done in 1.60 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.066339       -0.022345  0.260781 -0.363921  0.715917
AP006222.2      0.031489        0.000639  0.274726 -0.176861  0.859617
RP4-669L17.10   0.001947       -0.005773  0.248165 -0.113058  0.909984
RP11-206L10.9   0.026068       -0.001193  0.272140 -0.175444  0.860731
FAM87B          0.006367       -0.008010  0.240206 -0.116183  0.907507
...                  ...             ...       ...       ...       ...
MT-CYB         10.676399        0.306343  0.086479  3.867410  0.000110
AC145212.2      0.002041       -0.005834  0.248120 -0.113058  0.909984
AL592183.1      0.031330        0.015685  0.305056 -0.142590  0.886614
AC007325.4      0.013531        0.007887  0.300300 -0.125461  0.900159
AC240274.1      0.025493        0.024835  0.382705 -0.091041  0.927460

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-CYB         0.001138
AC145212.2          NaN
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Monocytes
CELL TYPE:  Monocytes ['Resistant' 'Remission']

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.16 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.17 seconds.

Fitting dispersion trend curve...
... done in 0.22 seconds.

Fitting MAP dispersions...
... done in 1.80 seconds.

Fitting LFCs...
... done in 1.12 seconds.

Calculating cook's distance...
... done in 0.42 seconds.

Replacing 28 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.93 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.049402        0.227833  0.924820  0.246354  0.805408
AP006222.2      0.057084        0.304659  1.082788  0.281366  0.778430
RP4-669L17.10   0.002926        0.236430  3.175586  0.074453  0.940650
RP11-206L10.9   0.022880        0.171042  2.163353  0.079064  0.936982
FAM87B          0.003584        0.236430  3.175586  0.074453  0.940650
...                  ...             ...       ...       ...       ...
MT-CYB         11.100368        0.280237  0.081889  3.422157  0.000621
AC145212.2      0.002050        0.244584  3.175617  0.077019  0.938608
AL592183.1      0.030674        0.177075  1.462033  0.121115  0.903600
AC007325.4      0.033171        0.235160  1.294615  0.181645  0.855862
AC240274.1      0.013321        0.290084  2.223319  0.130473  0.896192

                   padj
FO538757.2     0.974078
AP006222.2     0.974078
RP4-669L17.10  0.974078
RP11-206L10.9  0.974078
FAM87B         0.974078
...                 ...
MT-CYB         0.037498
AC145212.2     0.974078
AL592183.1     0.974078
AC007325.4     0.974078
AC240274.1     0.974078

[13566 rows x 6 columns]

... done in 1.59 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.049402        0.010475  0.223997  0.246354  0.805408
AP006222.2      0.057084        0.015420  0.235032  0.281366  0.778430
RP4-669L17.10   0.002926       -0.004533  0.202836  0.074453  0.940650
RP11-206L10.9   0.022880       -0.013238  0.197764  0.079064  0.936982
FAM87B          0.003584       -0.004788  0.202228  0.074453  0.940650
...                  ...             ...       ...       ...       ...
MT-CYB         11.100368        0.254933  0.082522  3.422157  0.000621
AC145212.2      0.002050       -0.003713  0.207599  0.077019  0.938608
AL592183.1      0.030674       -0.015602  0.209751  0.121115  0.903600
AC007325.4      0.033171        0.005023  0.226626  0.181645  0.855862
AC240274.1      0.013321        0.011507  0.269439  0.130473  0.896192

                   padj
FO538757.2     0.974078
AP006222.2     0.974078
RP4-669L17.10  0.974078
RP11-206L10.9  0.974078
FAM87B         0.974078
...                 ...
MT-CYB         0.037498
AC145212.2     0.974078
AL592183.1     0.974078
AC007325.4     0.974078
AC240274.1     0.974078

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE T cells
CELL TYPE:  T cells ['Resistant' 'Remission']

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.65 seconds.

Fitting dispersions...
... done in 1.92 seconds.

Fitting dispersion trend curve...
... done in 0.26 seconds.

Fitting MAP dispersions...
... done in 3.35 seconds.

Fitting LFCs...
... done in 1.96 seconds.

Calculating cook's distance...
... done in 1.93 seconds.

Replacing 19 outlier genes.

Fitting dispersions...
... done in 0.02 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 1.26 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.044934        0.208879  0.565679  0.369253  0.711939
AP006222.2      0.021392        0.222774  0.887653  0.250970  0.801837
RP4-669L17.10   0.001571        0.230713  3.122508  0.073887  0.941100
RP11-206L10.9   0.012982        0.225286  1.399182  0.161013  0.872084
FAM87B          0.000602        0.230246  3.122520  0.073737  0.941220
...                  ...             ...       ...       ...       ...
MT-CYB         10.193856        0.019497  0.040737  0.478600  0.632224
AC145212.2      0.002123        0.228774  3.122506  0.073266  0.941594
AL592183.1      0.021407        0.241604  0.887575  0.272206  0.785463
AC007325.4      0.011485        0.216390  1.213176  0.178366  0.858435
AC240274.1      0.006895        0.226291  1.858450  0.121763  0.903086

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-CYB         0.810269
AC145212.2          NaN
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13566 rows x 6 columns]

... done in 2.79 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.044934        0.000863  0.171970  0.369253  0.711939
AP006222.2      0.021392        0.002345  0.177920  0.250970  0.801837
RP4-669L17.10   0.001571        0.003174  0.214075  0.073887  0.941100
RP11-206L10.9   0.012982        0.001737  0.180212  0.161013  0.872084
FAM87B          0.000602        0.005443  0.258300  0.073737  0.941220
...                  ...             ...       ...       ...       ...
MT-CYB         10.193856        0.018132  0.040006  0.478600  0.632224
AC145212.2      0.002123        0.000816  0.190132  0.073266  0.941594
AL592183.1      0.021407        0.018761  0.189248  0.272206  0.785463
AC007325.4      0.011485       -0.002269  0.174615  0.178366  0.858435
AC240274.1      0.006895        0.002579  0.186069  0.121763  0.903086

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-CYB         0.810269
AC145212.2          NaN
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE DC
CELL TYPE:  DC ['Resistant' 'Remission']

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.27 seconds.

Fitting dispersions...
... done in 1.49 seconds.

Fitting dispersion trend curve...
... done in 0.22 seconds.

Fitting MAP dispersions...
... done in 2.37 seconds.

Fitting LFCs...
... done in 1.54 seconds.

Calculating cook's distance...
... done in 0.70 seconds.

Replacing 41 outlier genes.

Fitting dispersions...
... done in 0.02 seconds.

Fitting MAP dispersions...
... done in 0.02 seconds.

Fitting LFCs...
... done in 0.02 seconds.

Running Wald tests...
... done in 1.02 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.099513        0.418751  0.530299  0.789650  4.297319e-01
AP006222.2      0.095245        0.463782  0.495567  0.935861  3.493447e-01
RP4-669L17.10   0.006242        0.466761  2.972428  0.157030  8.752211e-01
RP11-206L10.9   0.025757        0.437353  1.356279  0.322466  7.471000e-01
FAM87B          0.008441        0.435219  2.203651  0.197499  8.434369e-01
...                  ...             ...       ...       ...           ...
MT-CYB         15.685021        0.551762  0.060149  9.173222  4.590885e-20
AC145212.2      0.002826        0.451558  2.972455  0.151914  8.792545e-01
AL592183.1      0.036989        0.430803  0.996886  0.432149  6.656329e-01
AC007325.4      0.025513        0.435523  1.221758  0.356473  7.214865e-01
AC240274.1      0.030831        0.529079  0.951657  0.555956  5.782412e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-CYB         3.609886e-18
AC145212.2              NaN
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13566 rows x 6 columns]

... done in 1.82 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.099513        0.022617  0.239944  0.789650  4.297319e-01
AP006222.2      0.095245        0.069871  0.255704  0.935861  3.493447e-01
RP4-669L17.10   0.006242        0.012701  0.458215  0.157030  8.752211e-01
RP11-206L10.9   0.025757       -0.008103  0.249088  0.322466  7.471000e-01
FAM87B          0.008441       -0.000171  0.254944  0.197499  8.434369e-01
...                  ...             ...       ...       ...           ...
MT-CYB         15.685021        0.541023  0.061202  9.173222  4.590885e-20
AC145212.2      0.002826        0.004204  0.288803  0.151914  8.792545e-01
AL592183.1      0.036989        0.011347  0.255164  0.432149  6.656329e-01
AC007325.4      0.025513        0.004562  0.256343  0.356473  7.214865e-01
AC240274.1      0.030831        0.044764  0.293037  0.555956  5.782412e-01

                       padj
FO538757.2              NaN
AP006222.2              NaN
RP4-669L17.10           NaN
RP11-206L10.9           NaN
FAM87B                  NaN
...                     ...
MT-CYB         3.609886e-18
AC145212.2              NaN
AL592183.1              NaN
AC007325.4              NaN
AC240274.1              NaN

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Plasma cells
CELL TYPE:  Plasma cells ['Resistant' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.13 seconds.

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.25 seconds.

Fitting MAP dispersions...
... done in 1.56 seconds.

Fitting LFCs...
... done in 1.28 seconds.

Calculating cook's distance...
... done in 0.31 seconds.

Replacing 37 outlier genes.

Fitting dispersions...
... done in 0.02 seconds.

Fitting MAP dispersions...
... done in 0.02 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.91 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.034243        0.381843  1.643443  0.232344  0.816271
AP006222.2      0.021177        0.342568  2.000077  0.171277  0.864006
RP4-669L17.10   0.000000             NaN       NaN       NaN       NaN
RP11-206L10.9   0.014124        0.465559  2.582831  0.180251  0.856955
FAM87B          0.000000             NaN       NaN       NaN       NaN
...                  ...             ...       ...       ...       ...
MT-CYB         16.740432        0.107309  0.112323  0.955355  0.339398
AC145212.2      0.005001        0.529973  3.240880  0.163528  0.870103
AL592183.1      0.036658        0.499374  1.560403  0.320029  0.748946
AC007325.4      0.058967        0.384890  1.290913  0.298153  0.765586
AC240274.1      0.007303        0.490846  3.240526  0.151471  0.879604

                   padj
FO538757.2     0.940263
AP006222.2     0.940263
RP4-669L17.10       NaN
RP11-206L10.9  0.940263
FAM87B              NaN
...                 ...
MT-CYB         0.940263
AC145212.2     0.940263
AL592183.1     0.940263
AC007325.4     0.940263
AC240274.1     0.940263

[13566 rows x 6 columns]

... done in 1.68 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.034243       -0.001333  0.327842  0.232344  0.816271
AP006222.2      0.021177       -0.013219  0.264445  0.171277  0.864006
RP4-669L17.10   0.000000             NaN       NaN       NaN       NaN
RP11-206L10.9   0.014124       -0.002044  0.326482  0.180251  0.856955
FAM87B          0.000000             NaN       NaN       NaN       NaN
...                  ...             ...       ...       ...       ...
MT-CYB         16.740432        0.080171  0.110558  0.955355  0.339398
AC145212.2      0.005001        0.004470  0.712666  0.163528  0.870103
AL592183.1      0.036658        0.007117  0.384644  0.320029  0.748946
AC007325.4      0.058967        0.004631  0.337563  0.298153  0.765586
AC240274.1      0.007303        0.001366  0.388967  0.151471  0.879604

                   padj
FO538757.2     0.940263
AP006222.2     0.940263
RP4-669L17.10       NaN
RP11-206L10.9  0.940263
FAM87B              NaN
...                 ...
MT-CYB         0.940263
AC145212.2     0.940263
AL592183.1     0.940263
AC007325.4     0.940263
AC240274.1     0.940263

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Endothelial cells
CELL TYPE:  Endothelial cells ['Resistant' 'Remission']

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 1.10 seconds.

Fitting dispersions...
... done in 2.17 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 4.79 seconds.

Fitting LFCs...
... done in 3.00 seconds.

Calculating cook's distance...
... done in 3.04 seconds.

Replacing 21 outlier genes.

Fitting dispersions...
... done in 0.02 seconds.

Fitting MAP dispersions...
... done in 0.02 seconds.

Fitting LFCs...
... done in 0.02 seconds.

Running Wald tests...
... done in 1.66 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.082579        0.205459  0.252937  0.812294  4.166228e-01
AP006222.2      0.082360        0.242961  0.266882  0.910371  3.626268e-01
RP4-669L17.10   0.004717        0.263334  2.041524  0.128989  8.973663e-01
RP11-206L10.9   0.013297        0.259281  1.003156  0.258466  7.960476e-01
FAM87B          0.000712        0.265743  2.889242  0.091977  9.267164e-01
...                  ...             ...       ...       ...           ...
MT-CYB         15.285886       -0.146328  0.025361 -5.769729  7.939917e-09
AC145212.2      0.002444        0.276848  2.462650  0.112419  9.104913e-01
AL592183.1      0.040523        0.269550  0.436874  0.616997  5.372366e-01
AC007325.4      0.023816        0.269443  0.642215  0.419553  6.748120e-01
AC240274.1      0.014431        0.277281  0.805040  0.344431  7.305223e-01

                       padj
FO538757.2     9.420291e-01
AP006222.2     9.420291e-01
RP4-669L17.10  9.420291e-01
RP11-206L10.9  9.420291e-01
FAM87B         9.420291e-01
...                     ...
MT-CYB         2.085152e-07
AC145212.2     9.420291e-01
AL592183.1     9.420291e-01
AC007325.4     9.420291e-01
AC240274.1     9.420291e-01

[13566 rows x 6 columns]

... done in 3.31 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
FO538757.2      0.082579       -0.049121  0.193810  0.812294  4.166228e-01
AP006222.2      0.082360        0.011820  0.193769  0.910371  3.626268e-01
RP4-669L17.10   0.004717       -0.000015  0.248063  0.128989  8.973663e-01
RP11-206L10.9   0.013297        0.003159  0.244489  0.258466  7.960476e-01
FAM87B          0.000712       -0.002550  0.227869  0.091977  9.267164e-01
...                  ...             ...       ...       ...           ...
MT-CYB         15.285886       -0.144042  0.025453 -5.769729  7.939917e-09
AC145212.2      0.002444        0.006455  0.348382  0.112419  9.104913e-01
AL592183.1      0.040523        0.051758  0.243123  0.616997  5.372366e-01
AC007325.4      0.023816        0.025519  0.250712  0.419553  6.748120e-01
AC240274.1      0.014431        0.020793  0.261094  0.344431  7.305223e-01

                       padj
FO538757.2     9.420291e-01
AP006222.2     9.420291e-01
RP4-669L17.10  9.420291e-01
RP11-206L10.9  9.420291e-01
FAM87B         9.420291e-01
...                     ...
MT-CYB         2.085152e-07
AC145212.2     9.420291e-01
AL592183.1     9.420291e-01
AC007325.4     9.420291e-01
AC240274.1     9.420291e-01

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE B cells
CELL TYPE:  B cells ['Resistant' 'Remission']

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.16 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 1.67 seconds.

Fitting LFCs...
... done in 1.18 seconds.

Calculating cook's distance...
... done in 0.39 seconds.

Replacing 36 outlier genes.

Fitting dispersions...
... done in 0.02 seconds.

Fitting MAP dispersions...
... done in 0.02 seconds.

Fitting LFCs...
... done in 0.02 seconds.

Running Wald tests...
... done in 0.90 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.036845       -0.144481  1.188400 -0.121576  0.903234
AP006222.2      0.039873       -0.068349  1.108160 -0.061678  0.950819
RP4-669L17.10   0.004541       -0.097225  2.984999 -0.032571  0.974016
RP11-206L10.9   0.029657       -0.168067  1.687874 -0.099573  0.920683
FAM87B          0.000000             NaN       NaN       NaN       NaN
...                  ...             ...       ...       ...       ...
MT-CYB         10.905954        0.029229  0.091424  0.319711  0.749188
AC145212.2      0.001738       -0.103145  2.985042 -0.034554  0.972435
AL592183.1      0.035130       -0.117054  1.280831 -0.091389  0.927184
AC007325.4      0.000913       -0.083189  2.985012 -0.027869  0.977767
AC240274.1      0.021661       -0.072902  2.063703 -0.035326  0.971820

                   padj
FO538757.2     0.999979
AP006222.2     0.999979
RP4-669L17.10  0.999979
RP11-206L10.9  0.999979
FAM87B              NaN
...                 ...
MT-CYB         0.999979
AC145212.2     0.999979
AL592183.1     0.999979
AC007325.4     0.999979
AC240274.1     0.999979

[13566 rows x 6 columns]

... done in 1.81 seconds.

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.03 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.036845       -0.008511  0.190706 -0.121576  0.903234
AP006222.2      0.039873        0.004799  0.205735 -0.061678  0.950819
RP4-669L17.10   0.004541        0.002201  0.223440 -0.032571  0.974016
RP11-206L10.9   0.029657       -0.012291  0.175742 -0.099573  0.920683
FAM87B          0.000000             NaN       NaN       NaN       NaN
...                  ...             ...       ...       ...       ...
MT-CYB         10.905954        0.021823  0.084597  0.319711  0.749188
AC145212.2      0.001738       -0.000978  0.200486 -0.034554  0.972435
AL592183.1      0.035130       -0.000488  0.197859 -0.091389  0.927184
AC007325.4      0.000913        0.004390  0.316118 -0.027869  0.977767
AC240274.1      0.021661        0.003038  0.216078 -0.035326  0.971820

                   padj
FO538757.2     0.999979
AP006222.2     0.999979
RP4-669L17.10  0.999979
RP11-206L10.9  0.999979
FAM87B              NaN
...                 ...
MT-CYB         0.999979
AC145212.2     0.999979
AL592183.1     0.999979
AC007325.4     0.999979
AC240274.1     0.999979

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE pDC
CELL TYPE:  pDC ['Resistant']





-------------------------------------------------------------------------------------

HERE Epithelial cells
CELL TYPE:  Epithelial cells ['Resistant' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.82 seconds.

Fitting dispersion trend curve...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 1.22 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 10 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.82 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.026770       -0.907849  2.993686 -0.303255  0.761696
AP006222.2      0.087318       -0.937982  1.206237 -0.777610  0.436799
RP4-669L17.10   0.000000             NaN       NaN       NaN       NaN
RP11-206L10.9   0.024735       -1.030632  2.996988 -0.343889  0.730930
FAM87B          0.033044       -1.183012  2.996816 -0.394756  0.693023
...                  ...             ...       ...       ...       ...
MT-CYB         16.566781       -0.457790  0.123170 -3.716741  0.000202
AC145212.2      0.000000             NaN       NaN       NaN       NaN
AL592183.1      0.000000             NaN       NaN       NaN       NaN
AC007325.4      0.016598       -0.907849  2.993686 -0.303255  0.761696
AC240274.1      0.020486       -1.137152  2.997773 -0.379332  0.704441

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-CYB         0.002987
AC145212.2          NaN
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13566 rows x 6 columns]

/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/ihome/rgottschalk/cil8/envs/rnaseq/lib/python3.13/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 2.92 seconds.

/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
/scratch/slurm-7886343/ipykernel_3240348/1152440307.py:20: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
Fitting size factors...
... done in 0.02 seconds.

Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.026770    1.042193e-07  0.001636 -0.303255  0.761696
AP006222.2      0.087318   -2.922056e-07  0.001348 -0.777610  0.436799
RP4-669L17.10   0.000000             NaN       NaN       NaN       NaN
RP11-206L10.9   0.024735   -1.020012e-07  0.001284 -0.343889  0.730930
FAM87B          0.033044   -2.576702e-07  0.001063 -0.394756  0.693023
...                  ...             ...       ...       ...       ...
MT-CYB         16.566781   -3.761568e-01  0.132192 -3.716741  0.000202
AC145212.2      0.000000             NaN       NaN       NaN       NaN
AL592183.1      0.000000             NaN       NaN       NaN       NaN
AC007325.4      0.016598    8.027428e-08  0.001599 -0.303255  0.761696
AC240274.1      0.020486   -2.340479e-07  0.001087 -0.379332  0.704441

                   padj
FO538757.2          NaN
AP006222.2          NaN
RP4-669L17.10       NaN
RP11-206L10.9       NaN
FAM87B              NaN
...                 ...
MT-CYB         0.002987
AC145212.2          NaN
AL592183.1          NaN
AC007325.4          NaN
AC240274.1          NaN

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Macrophages
CELL TYPE:  Macrophages ['Resistant' 'Remission']
Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.63 seconds.

Fitting dispersion trend curve...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 1.02 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 28 outlier genes.

Fitting dispersions...
... done in 0.01 seconds.

Fitting MAP dispersions...
... done in 0.01 seconds.

Fitting LFCs...
... done in 0.01 seconds.

Running Wald tests...
... done in 0.82 seconds.

Fitting MAP LFCs...

Log2 fold change & Wald test p-value: Group Resistant vs Remission
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.071087        0.745386  4.230967  0.176174  0.860157
AP006222.2      0.075148        0.686836  3.461900  0.198398  0.842733
RP4-669L17.10   0.000000             NaN       NaN       NaN       NaN
RP11-206L10.9   0.013872        0.381818  4.969648  0.076830  0.938759
FAM87B          0.000000             NaN       NaN       NaN       NaN
...                  ...             ...       ...       ...       ...
MT-CYB         13.686736        0.302760  0.375139  0.807062  0.419631
AC145212.2      0.000000             NaN       NaN       NaN       NaN
AL592183.1      0.021086        0.323033  4.968741  0.065013  0.948164
AC007325.4      0.086246        0.145413  4.316925  0.033684  0.973129
AC240274.1      0.047664        0.862711  4.912115  0.175629  0.860585

                   padj
FO538757.2     0.999936
AP006222.2     0.999936
RP4-669L17.10       NaN
RP11-206L10.9  0.999936
FAM87B              NaN
...                 ...
MT-CYB         0.999936
AC145212.2          NaN
AL592183.1     0.999936
AC007325.4     0.999936
AC240274.1     0.999936

[13566 rows x 6 columns]
Shrunk log2 fold change & Wald test p-value: Group[T.Resistant]
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
FO538757.2      0.071087        0.001740  0.136559  0.176174  0.860157
AP006222.2      0.075148        0.002074  0.132876  0.198398  0.842733
RP4-669L17.10   0.000000             NaN       NaN       NaN       NaN
RP11-206L10.9   0.013872       -0.000431  0.122971  0.076830  0.938759
FAM87B          0.000000             NaN       NaN       NaN       NaN
...                  ...             ...       ...       ...       ...
MT-CYB         13.686736        0.029381  0.124463  0.807062  0.419631
AC145212.2      0.000000             NaN       NaN       NaN       NaN
AL592183.1      0.021086       -0.000545  0.122140  0.065013  0.948164
AC007325.4      0.086246       -0.001019  0.121179  0.033684  0.973129
AC240274.1      0.047664        0.003783  0.158574  0.175629  0.860585

                   padj
FO538757.2     0.999936
AP006222.2     0.999936
RP4-669L17.10       NaN
RP11-206L10.9  0.999936
FAM87B              NaN
...                 ...
MT-CYB         0.999936
AC145212.2          NaN
AL592183.1     0.999936
AC007325.4     0.999936
AC240274.1     0.999936

[13566 rows x 6 columns]





-------------------------------------------------------------------------------------

HERE Mast cells
CELL TYPE:  Mast cells ['Remission']





-------------------------------------------------------------------------------------

HERE Double-positive thymocytes
CELL TYPE:  Double-positive thymocytes ['Remission']

... done in 1.01 seconds.

In [8]:
# concat results across cell types
dea_df = pd.concat(dea_results)
dea_df = dea_df.reset_index().rename(columns={'level_0': groupby,'level_1':'index'}).set_index('index')
dea_df.head()

,cell_type,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
index,,,,,,,
FO538757.2,Fibroblasts,0.131050,-0.091905,0.159709,-2.682612,0.007305,0.012344
AP006222.2,Fibroblasts,0.187213,0.009762,0.128138,-2.908755,0.003629,0.006663
RP4-669L17.10,Fibroblasts,0.006052,-0.013115,0.418037,-0.290787,0.771214,NaN
RP11-206L10.9,Fibroblasts,0.027362,-0.007938,0.322249,-0.956574,0.338782,NaN
FAM87B,Fibroblasts,0.010532,-0.158460,0.416020,-0.592839,0.553289,NaN

In [9]:
# PyDeseq Seems to intrdoce NAs for some p-values
# NOTE: there sometimes some NaN being introduced, best to double check that, in this case it's only for a single gene, but it might be a problem.
len(dea_df[dea_df.isna().any(axis=1)])
#dea_df.to_csv("deseq_results.csv")

67437

In [10]:
#adata = adata[adata.obs[condition_key]=='Resistant'].copy()
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

In [11]:
lr_res = li.multi.df_to_lr(adata,
                           dea_df=dea_df,
                           resource_name='consensus', # NOTE: uses HUMAN gene symbols!
                           expr_prop=0.1, # calculated for adata as passed - used to filter interactions
                           groupby="cell_type",
                           stat_keys=['stat', 'pvalue', 'padj'],
                           use_raw=False,
                           complex_col='stat', # NOTE: we use the Wald Stat to deal with complexes
                           verbose=True,
                           return_all_lrs=False,
                           )
lr_res

Using resource `consensus`.
Using `.X`!
Converting to sparse csr matrix!
0.47 of entities in the resource are missing from the data.

,ligand,receptor,ligand_complex,receptor_complex,source,ligand_stat,ligand_pvalue,ligand_padj,ligand_expr,ligand_props,...,receptor_pvalue,receptor_padj,receptor_expr,receptor_props,interaction_stat,interaction_pvalue,interaction_padj,interaction_expr,interaction_props,interaction
0,HLA-A,APLP2,HLA-A,APLP2,B cells,-2.716304,6.601522e-03,4.031935e-01,2.481005,0.908184,...,0.069615,0.999979,0.366725,0.205589,-2.265356,0.038108,0.701586,1.423865,0.556886,HLA-A^APLP2
1,APP,CD74,APP,CD74,B cells,-0.214305,8.303093e-01,9.999791e-01,0.255581,0.149701,...,0.591446,0.999979,3.932141,0.866267,0.161219,0.710877,0.999979,2.093861,0.507984,APP^CD74
2,APP,LRP10,APP,LRP10,B cells,-0.214305,8.303093e-01,9.999791e-01,0.255581,0.149701,...,0.670102,0.999979,0.266437,0.169661,-0.320157,0.750206,0.999979,0.261009,0.159681,APP^LRP10
3,ICAM1,IL2RG,ICAM1,IL2RG,B cells,-0.219842,8.259945e-01,9.999791e-01,0.148276,0.105788,...,0.022469,0.999979,0.529499,0.313373,-1.251095,0.424232,0.999979,0.338887,0.209581,ICAM1^IL2RG
4,CD55,ADGRE5,CD55,ADGRE5,B cells,-6.475906,9.424486e-11,5.280581e-08,1.032140,0.524950,...,0.631257,0.999979,0.217973,0.145709,-3.477932,0.315629,0.499990,0.625056,0.335329,CD55^ADGRE5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25794,LGALS3,ENG,LGALS3,ENG,Mo-mac,10.635098,2.046141e-26,3.415792e-24,2.004810,0.915556,...,0.091965,0.523381,0.608003,0.467071,6.160109,0.045983,0.261691,1.306407,0.691313,LGALS3^ENG
25795,CD59,STAB1,CD59,STAB1,Mo-mac,-5.191387,2.087329e-07,5.819560e-06,0.688472,0.479596,...,0.984505,0.985818,0.504747,0.368485,-2.605404,0.492253,0.492912,0.596610,0.424040,CD59^STAB1
25796,TGFB1,LPP,TGFB1,LPP,Mo-mac,-0.436133,6.627402e-01,9.234078e-01,0.335165,0.281616,...,0.001709,0.021965,0.188294,0.166061,1.350260,0.332225,0.472687,0.261730,0.223838,TGFB1^LPP
25797,ENTPD1,TMIGD3,ENTPD1,TMIGD3,Mo-mac,1.431852,1.521862e-01,7.078987e-01,0.115126,0.106263,...,0.231967,0.877001,0.150490,0.112323,1.313579,0.192077,0.792450,0.132808,0.109293,ENTPD1^TMIGD3
25798,MAML2,NOTCH2,MAML2,NOTCH2,Mo-mac,0.838058,4.019984e-01,9.234078e-01,0.121876,0.110303,...,0.140858,0.676806,0.143485,0.129293,1.155331,0.271428,0.800107,0.132680,0.119798,MAML2^NOTCH2

In [12]:
lr_res["target"].value_counts()

target
Macrophages          2770
DC                   2662
Mo-mac               2627
TRM                  2408
Monocytes            2172
Fibroblasts          2147
Epithelial cells     2006
Endothelial cells    1909
ILC                  1705
Plasma cells         1526
T cells              1366
B cells               938
Name: count, dtype: int64

In [13]:
lr_res = lr_res.sort_values("interaction_stat", ascending=False, key=abs)
# Select all of the interactions with macrophages are the target
lr_res = lr_res[lr_res["target"] == TARGET_CELL]
lr_res.head(10)

,ligand,receptor,ligand_complex,receptor_complex,source,ligand_stat,ligand_pvalue,ligand_padj,ligand_expr,ligand_props,...,receptor_pvalue,receptor_padj,receptor_expr,receptor_props,interaction_stat,interaction_pvalue,interaction_padj,interaction_expr,interaction_props,interaction
10874,HLA-C,LILRB1,HLA-C,LILRB1,Fibroblasts,-45.270855,0.000000e+00,0.000000e+00,2.056362,0.898455,...,3.810861e-04,0.001706,0.193607,0.173010,-20.859004,1.905431e-04,0.000853,1.124985,0.535733,HLA-C^LILRB1
25323,HLA-DRB5,CD4,HLA-DRB5,CD4,Mo-mac,-46.101465,0.000000e+00,0.000000e+00,1.223120,0.467879,...,6.652880e-07,0.000006,0.657954,0.487313,-20.565116,3.326440e-07,0.000003,0.940537,0.477596,HLA-DRB5^CD4
10873,HLA-C,LILRB2,HLA-C,LILRB2,Fibroblasts,-45.270855,0.000000e+00,0.000000e+00,2.056362,0.898455,...,2.497423e-07,0.000002,0.271875,0.227220,-20.056480,1.248711e-07,0.000001,1.164119,0.562838,HLA-C^LILRB2
5631,HLA-C,LILRB1,HLA-C,LILRB1,Endothelial cells,-42.533638,0.000000e+00,0.000000e+00,2.658099,0.961035,...,3.810861e-04,0.001706,0.193607,0.173010,-19.490396,1.905431e-04,0.000853,1.425853,0.567023,HLA-C^LILRB1
25500,HSPA1A,TLR4,HSPA1A,TLR4,Mo-mac,-39.942750,0.000000e+00,0.000000e+00,1.680223,0.640000,...,1.351671e-02,0.032873,0.197269,0.170704,-18.736446,6.758357e-03,0.016437,0.938746,0.405352,HSPA1A^TLR4
5630,HLA-C,LILRB2,HLA-C,LILRB2,Endothelial cells,-42.533638,0.000000e+00,0.000000e+00,2.658099,0.961035,...,2.497423e-07,0.000002,0.271875,0.227220,-18.687872,1.248711e-07,0.000001,1.464987,0.594128,HLA-C^LILRB2
5606,HLA-B,LILRB1,HLA-B,LILRB1,Endothelial cells,-40.289000,0.000000e+00,0.000000e+00,3.280686,0.985723,...,3.810861e-04,0.001706,0.193607,0.173010,-18.368076,1.905431e-04,0.000853,1.737147,0.579367,HLA-B^LILRB1
22785,HLA-DRB5,CD4,HLA-DRB5,CD4,TRM,-40.643057,0.000000e+00,0.000000e+00,1.243361,0.468858,...,6.652880e-07,0.000006,0.657954,0.487313,-17.835913,3.326440e-07,0.000003,0.950657,0.478085,HLA-DRB5^CD4
5605,HLA-B,LILRB2,HLA-B,LILRB2,Endothelial cells,-40.289000,0.000000e+00,0.000000e+00,3.280686,0.985723,...,2.497423e-07,0.000002,0.271875,0.227220,-17.565553,1.248711e-07,0.000001,1.776281,0.606472,HLA-B^LILRB2
11049,COL14A1,CD44,COL14A1,CD44,Fibroblasts,29.226379,8.965315e-188,4.813093e-185,1.462697,0.692743,...,4.077403e-04,0.001798,1.333200,0.768743,16.380701,2.038701e-04,0.000899,1.397949,0.730743,COL14A1^CD44

In [14]:
lr_res.to_csv(output_fname, index=False)